"""Template 10: Psychology & Mental Health"""

TEMPLATE_DATA = {
    "template_name": "psychology-mental-health",
    "template_category": "niche",
    "is_active": True,
    "popularity_order": 10,
    "name": "Psychology & Mental Health",
    "description": "Evidence-based psychology and mental wellness content covering emotional intelligence, attachment theory, cognitive behavioral insights, and practical mental health strategies.",
    "niche_name": "Psychology & Mental Health",
    "niche_description": "Evidence-based psychology and mental wellness content using clinically-informed frameworks to help adults understand their emotions, relationships, and behavioral patterns.",
    "content_brief": "Evidence-based psychology and mental wellness content for adults aged 20–45 in English-speaking countries (US, UK, Canada, Australia), focusing on emotional intelligence, attachment theory, cognitive behavioral insights, and practical mental health strategies. Topics include: understanding anxiety and depression through a neuroscience lens, attachment styles and how they shape relationships, setting boundaries without guilt, the psychology of people-pleasing and codependency, emotional regulation techniques backed by clinical research, trauma-informed self-awareness (without replacing therapy), the neuroscience of stress and burnout recovery, understanding narcissistic and toxic relationship dynamics, the science of self-esteem vs self-compassion, and reframing negative thought patterns. Tone is warm, validating, and clinically informed — like a therapist who explains the 'why' behind emotional patterns. Uses specific psychological frameworks (CBT, ACT, polyvagal theory, attachment theory) while keeping language accessible. The style is gentle revelation — helping people see their own patterns clearly without shame. Target audience is emotionally intelligent adults who want to understand themselves and their relationships better through a psychological lens. Content philosophy: understanding the science behind your emotions is the first step to changing your relationship with them — knowledge is the bridge between suffering and healing.",
    "target_audience": "Adults 20-45, US/UK/Canada/Australia",
    "audience_description": "Emotionally intelligent adults who want to understand themselves and their relationships better through a psychological lens. They're curious, self-aware, and open to growth but want science, not platitudes.",
    "content_tone": ["warm", "validating", "clinically informed", "gentle", "insightful"],
    "tone_avoid": ["diagnosing viewers", "replacing professional therapy", "toxic positivity", "shame-based framing"],
    "topic_categories": ["Attachment Theory", "Anxiety & Depression", "Boundaries", "Emotional Regulation", "Relationship Patterns", "Burnout", "People-Pleasing", "Trauma Awareness"],
    "topic_keywords": ["attachment styles", "people pleasing", "emotional regulation", "cognitive behavioral therapy", "polyvagal theory", "boundaries", "anxiety", "burnout", "self-compassion", "trauma response"],
    "topic_avoid": ["clinical diagnosis content", "specific medication advice", "crisis intervention claims", "replacement for professional therapy"],
    "content_philosophy": "Understanding the science behind your emotions is the first step to changing your relationship with them — knowledge is the bridge between suffering and healing. We illuminate patterns, not pathologies.",
    "hook_themes": ["why you react the way you do", "the psychology behind common patterns", "what your nervous system is telling you", "attachment patterns explained", "the science of emotional health"],
    "reel_examples": [
        {"title": "7 SIGNS YOU GREW UP WITH EMOTIONAL NEGLECT", "content_lines": []},
        {"title": "THINGS EMOTIONALLY INTELLIGENT PEOPLE NEVER DO", "content_lines": []},
        {"title": "YOUR ATTACHMENT STYLE EXPLAINED IN 60 SECONDS", "content_lines": []},
        {"title": "5 SIGNS YOU'RE A PEOPLE PLEASER (AND WHY)", "content_lines": []},
        {"title": "HOW TO SET BOUNDARIES WITHOUT FEELING GUILTY", "content_lines": []},
        {"title": "TOXIC RELATIONSHIP PATTERNS YOU MIGHT NOT RECOGNIZE", "content_lines": []},
        {"title": "WHY YOU FEEL DRAINED AFTER BEING AROUND CERTAIN PEOPLE", "content_lines": []},
        {"title": "8 SIGNS YOUR ANXIETY IS TRYING TO TELL YOU SOMETHING", "content_lines": []},
        {"title": "THE PSYCHOLOGY OF WHY YOU SELF-SABOTAGE", "content_lines": []},
        {"title": "THINGS A THERAPIST WANTS YOU TO KNOW", "content_lines": []},
    ],
    "post_examples": [
        {
            "title": "HOW YOUR ATTACHMENT STYLE SHAPES EVERY RELATIONSHIP YOU HAVE",
            "slides": [
                "Attachment theory research by Dr. Amir Levine at Columbia University (2023 update) showed that approximately 50% of adults have a secure attachment style, 25% anxious-preoccupied, 20% avoidant-dismissive, and 5% fearful-avoidant. Your style — formed in childhood — predicts relationship patterns with 70-80% accuracy.",
                "A study in the Journal of Personality and Social Psychology (2022) found that anxious-attached individuals send an average of 3x more 'checking in' messages and interpret silence as rejection, while avoidant-attached individuals need 48% more physical and emotional space to feel comfortable. Neither is 'wrong' — but without awareness, these styles create painful cycles.",
                "Neuroscience research from UCLA (2023) showed that attachment patterns are literally wired into the nervous system — anxious attachment is associated with heightened amygdala (threat center) activation, while avoidant attachment shows suppressed prefrontal-limbic connectivity. These are not character flaws; they're adaptive survival strategies from childhood.",
                "Importantly, a longitudinal study from the University of Minnesota (2022) tracking participants over 20 years showed that attachment styles can shift toward security through two paths: a consistently secure romantic partner (earned security through relationship) or targeted therapy (earned security through self-work). You are not permanently locked into your childhood pattern.",
            ],
            "study_ref": "Columbia University, Dr. Amir Levine, 2023 + University of Minnesota, 2022",
        },
        {
            "title": "WHY SETTING BOUNDARIES FEELS SO HARD (THE NEUROSCIENCE)",
            "slides": [
                "Neuroscience research from the University of Amsterdam (2023) showed that saying 'no' to someone activates the same brain regions as physical pain (anterior cingulate cortex and insula). For people raised in environments where boundaries were punished, this response is amplified by 40-60% — setting boundaries literally hurts more.",
                "A study in the Journal of Clinical Psychology (2022) found that individuals with poor boundaries experienced 58% higher rates of burnout, 43% more relationship conflict, and 31% lower self-esteem than those with clear boundaries. The short-term pain of saying no prevents the long-term pain of resentment and exhaustion.",
                "Cognitive behavioral research from the University of Pennsylvania (2023) showed that the 'guilt response' after setting a boundary typically lasts 20-45 minutes and then naturally subsides — but most people retract their boundary within the first 10 minutes because the discomfort feels intolerable. Knowing it's temporary is the key to sitting through it.",
                "Clinical therapy data from the Gottman Institute (2022) found that relationships where both partners set and respect boundaries had 67% higher satisfaction scores. Boundaries don't push people away — they create the safety that allows genuine closeness. The people who leave when you set boundaries are the reason you needed boundaries in the first place.",
            ],
            "study_ref": "University of Amsterdam, 2023 + Gottman Institute, 2022",
        },
        {
            "title": "THE SCIENCE OF BURNOUT: WHAT'S ACTUALLY HAPPENING IN YOUR BRAIN",
            "slides": [
                "Research from the Karolinska Institute, Sweden (2023) using brain imaging showed that chronic work stress physically shrinks the prefrontal cortex (decision-making, emotional regulation) and enlarges the amygdala (threat response). Burnout isn't just 'being tired' — it's measurable brain structure changes that impair cognitive and emotional function.",
                "A World Health Organization study (2022) classified burnout by three dimensions: emotional exhaustion (feeling drained), depersonalization (cynicism and detachment), and reduced personal accomplishment (feeling ineffective). Addressing only one dimension while ignoring the others leads to incomplete recovery.",
                "Recovery research from the University of Zurich (2023) found that burnout recovery takes an average of 1-3 years with active intervention — and many people attempt to recover while continuing the same workload, which research shows is 'like trying to fill a bathtub with the drain open.' True recovery requires structural changes, not just vacation.",
                "Prevention data from Gallup (2022) identified the five strongest burnout predictors: unfair treatment at work, unmanageable workload, unclear communication from managers, lack of manager support, and unreasonable time pressure. Notably, passion for the work was not protective — in fact, highly passionate workers burn out faster because they override their own warning signals.",
            ],
            "study_ref": "Karolinska Institute, 2023 + Gallup Burnout Research, 2022",
        },
        {
            "title": "PEOPLE-PLEASING IS A TRAUMA RESPONSE (HERE'S THE PSYCHOLOGY)",
            "slides": [
                "Clinical research from the University of California, Berkeley (2023) identified people-pleasing as a 'fawn' response — one of four survival strategies (fight, flight, freeze, fawn) that develop in response to threatening environments. Children who learned that compliance prevented punishment develop automatic people-pleasing wiring that persists into adulthood.",
                "A study in the Journal of Counseling Psychology (2022) found that chronic people-pleasers had 67% higher rates of anxiety, 54% higher rates of depression, and 71% higher rates of relationship dissatisfaction. The pattern creates a paradox: the harder you try to make everyone happy, the less happy you become.",
                "Neuroscience research from the Social Brain Lab at the University of Cambridge (2023) showed that people-pleasers have hyperactive 'mentalizing networks' — brain regions that constantly monitor others' emotional states. This isn't empathy; it's hypervigilance disguised as caring. The difference: empathy is 'I sense your feelings'; hypervigilance is 'I need to fix your feelings to feel safe.'",
                "Recovery research from Acceptance and Commitment Therapy (ACT) trials at the University of Nevada (2022) showed that the most effective intervention is values clarification — identifying what matters to you independent of others' approval. Participants who completed a 6-week values-based program reduced people-pleasing behaviors by 41% and increased life satisfaction by 33%.",
            ],
            "study_ref": "UC Berkeley, 2023 + University of Nevada ACT Trials, 2022",
        },
        {
            "title": "HOW NEGATIVE SELF-TALK LITERALLY REWIRES YOUR BRAIN",
            "slides": [
                "Neuroplasticity research from the University of Wisconsin-Madison (2023) showed that repetitive negative thoughts strengthen neural pathways associated with depression and anxiety — the brain literally builds highways for negativity. After just 2 weeks of persistent negative self-talk, fMRI scans show measurably increased activity in self-criticism circuits.",
                "A study in Behaviour Research & Therapy (2022) found that the average person has 6,200 thoughts per day, and those with depression have up to 80% negative thought content compared to 30-40% in non-depressed individuals. The content of thoughts matters less than the ratio — it's the overwhelming proportion that creates the depressive state.",
                "Cognitive behavioral research from Beck Institute (2023) showed that 'cognitive restructuring' — identifying and challenging negative thoughts — reduced depressive symptoms by 43% in 12 weeks. The technique isn't positive thinking; it's accurate thinking — replacing 'I always fail' with 'I failed at this specific thing, and here's what I can learn.'",
                "Self-compassion research from Dr. Kristin Neff at the University of Texas (2022) found that self-compassion (treating yourself as you'd treat a friend) was more effective than self-esteem building for reducing negative self-talk. Self-esteem is conditional ('I'm good because I succeeded'); self-compassion is unconditional ('I'm struggling, and that's human'). The latter reduced intrusive negative thoughts by 52%.",
            ],
            "study_ref": "University of Wisconsin-Madison, 2023 + Dr. Kristin Neff, University of Texas, 2022",
        },
        {
            "title": "WHY YOU ATTRACT THE SAME TOXIC RELATIONSHIP PATTERNS",
            "slides": [
                "Attachment and relationship research from the Kinsey Institute (2023) found that people unconsciously seek partners who confirm their existing beliefs about relationships — a phenomenon called 'confirmation bias in love.' If you believe you're not worthy of care, you'll unconsciously filter for partners who reinforce that belief.",
                "A study in the Journal of Family Psychology (2022) showed that unresolved childhood relational patterns repeat in adult relationships with 78% predictability. The 'repetition compulsion' drives people to recreate familiar dynamics — even painful ones — because the brain equates familiarity with safety.",
                "Neuroscience research from Emory University (2023) demonstrated that the 'chemistry' and 'spark' people feel with certain partners is often the nervous system recognizing familiar activation patterns — not genuine compatibility. A calm, secure relationship can initially feel 'boring' to someone whose nervous system was calibrated by chaos.",
                "Clinical data from the Gottman Institute (2022) showed that breaking the cycle requires two things: awareness of the pattern (therapy, journaling, or honest self-reflection) and tolerating the discomfort of a different choice. Patients who consciously chose 'boring' (secure, available) partners reported 3x higher relationship satisfaction at the 2-year mark.",
            ],
            "study_ref": "Kinsey Institute, 2023 + Gottman Institute, 2022",
        },
        {
            "title": "THE PSYCHOLOGY OF WHY YOU PROCRASTINATE ON THINGS THAT MATTER MOST",
            "slides": [
                "Research from the University of Sheffield (2023) using Temporal Motivation Theory showed that procrastination increases exponentially when a task has high personal significance. The more something matters to you (career change, creative project, difficult conversation), the more anxiety it triggers — and avoidance is the brain's fastest anxiety-reduction strategy.",
                "A study in the Journal of Behavioral Decision Making (2022) found that perfectionism was the strongest predictor of procrastination — not laziness. Perfectionists delay starting because they can't tolerate the gap between their vision and their current ability. The irony: perfectionists produce less than non-perfectionists because they start less often.",
                "Neuroscience data from the University of Colorado (2023) showed that the prefrontal cortex (future planning) and the limbic system (present comfort) compete in real-time when facing difficult tasks. In procrastinators, the limbic system wins 73% of the time — the immediate relief of avoidance outweighs the abstract future benefit of completing the task.",
                "Cognitive behavioral intervention data from Stockholm University (2022) showed that 'psychological exposure' — doing the feared task for just 5 minutes — reduced task anxiety by 38% and increased follow-through by 72%. The hardest part is always the first 5 minutes. Once you're in motion, the brain's 'completion drive' (Zeigarnik effect) takes over.",
            ],
            "study_ref": "University of Sheffield, 2023 + Stockholm University, 2022",
        },
        {
            "title": "EMOTIONAL REGULATION: THE SKILL NOBODY TAUGHT YOU",
            "slides": [
                "Research from Yale's Center for Emotional Intelligence (2023) found that only 36% of people can accurately identify more than three emotions they're feeling at any given time. This 'emotional granularity' deficit means most people experience complex emotions as a vague 'bad feeling' — and you can't regulate what you can't name.",
                "A study in the Journal of Personality and Social Psychology (2022) showed that people who could label their emotions with specificity (distinguishing 'disappointed' from 'frustrated' from 'overwhelmed') had 30% better emotional regulation than those who used generic terms like 'stressed' or 'upset.' Precision in naming creates precision in responding.",
                "Polyvagal theory research from Dr. Stephen Porges (2023 update) showed that the vagus nerve — connecting brain to gut — can be consciously activated through slow exhaling (longer out-breath than in-breath), humming, and cold exposure. A 4-7-8 breathing pattern (inhale 4, hold 7, exhale 8) reduces sympathetic nervous system activation by 40% within 90 seconds.",
                "Clinical outcome data from Dialectical Behavior Therapy (DBT) trials at the University of Washington (2022) showed that teaching four emotion regulation skills — mindfulness, distress tolerance, emotion labeling, and interpersonal effectiveness — reduced emotional crisis episodes by 50% in 6 months. These skills aren't innate talent; they're learnable techniques.",
            ],
            "study_ref": "Yale Center for Emotional Intelligence, 2023 + Dr. Stephen Porges, 2023",
        },
        {
            "title": "THE NEUROSCIENCE OF ANXIETY (WHAT YOUR BRAIN IS ACTUALLY DOING)",
            "slides": [
                "Research from the National Institute of Mental Health (2023) showed that anxiety disorders affect 31% of adults at some point — making it the most common mental health condition worldwide. Yet 63% of people with anxiety don't receive treatment, often because they believe anxiety is a character flaw rather than a neurological pattern.",
                "Neuroimaging studies from Cambridge University (2022) revealed that anxious brains show a hyperactive amygdala that fires 60% more frequently at ambiguous stimuli (faces with neutral expressions, uncertain situations) compared to non-anxious brains. Anxiety isn't seeing threats that aren't there — it's the brain interpreting 'maybe' as 'definitely dangerous.'",
                "A study in JAMA Psychiatry (2023) found that regular aerobic exercise (30 minutes, 3x per week) reduced anxiety symptoms by 26% — comparable to SSRI medication in mild-to-moderate cases. Exercise directly increases GABA (the brain's calming neurotransmitter) and reduces cortisol, addressing the neurochemical imbalance that drives anxiety.",
                "Exposure therapy meta-analysis from the University of Amsterdam (2022) showed that gradually facing feared situations (with support) reduced anxiety by 60-80% in 12-16 sessions — the most effective treatment known. The mechanism: repeated safe exposure teaches the amygdala that the feared situation is survivable, literally rewiring the threat response.",
            ],
            "study_ref": "National Institute of Mental Health, 2023 + JAMA Psychiatry, 2023",
        },
        {
            "title": "WHY 'JUST THINK POSITIVE' DOESN'T WORK (AND WHAT DOES)",
            "slides": [
                "Research from the University of Waterloo (2023) found that positive affirmations actually made people with low self-esteem feel worse. When there's a large gap between the affirmation ('I am worthy of love') and the person's actual belief, the brain registers the mismatch as cognitive dissonance — increasing distress rather than reducing it.",
                "A study in Psychological Science (2022) showed that 'toxic positivity' — the pressure to suppress negative emotions — increased psychological distress by 38% compared to allowing natural emotional expression. Emotions suppressed don't disappear; they intensify internally and eventually emerge as anxiety, depression, or somatic symptoms.",
                "Acceptance and Commitment Therapy (ACT) research from the University of Nevada (2023) demonstrated that 'cognitive defusion' — observing thoughts without believing them ('I notice I'm having the thought that I'm not good enough') — reduced the behavioral impact of negative thoughts by 45%. The goal isn't positive thinking; it's creating distance from all thoughts.",
                "Research from Dr. Susan David at Harvard Medical School (2022) showed that 'emotional agility' — the ability to experience difficult emotions without being controlled by them — was the strongest predictor of well-being, resilience, and life satisfaction across 70,000 participants. The healthiest people aren't the most positive — they're the most emotionally flexible.",
            ],
            "study_ref": "University of Waterloo, 2023 + Dr. Susan David, Harvard Medical School, 2022",
        },
    ],
    "image_style_description": "Soft, calming visual aesthetic with muted blues, greens, and warm neutrals. Brain illustrations, minimal diagrams, and thoughtful human imagery that feels warm and safe.",
    "image_palette_keywords": ["soft blue", "warm neutral", "green", "calming", "minimal", "human-centered"],
    "brand_personality": "A warm, clinically-informed friend who explains the 'why' behind your emotional patterns — creating gentle revelations that lead to real change, without shame or judgment.",
    "brand_focus_areas": ["attachment theory", "emotional regulation", "anxiety & burnout", "relationship patterns", "self-compassion"],
    "parent_brand_name": "",
    "cta_options": [
        {"text": "Follow for psychology insights that help you understand yourself", "weight": 34},
        {"text": "If you want to understand your mind better, follow our page!", "weight": 33},
        {"text": "Save this — share it with someone who needs it", "weight": 33},
    ],
    "hashtags": ["#psychology", "#mentalhealth", "#emotionalintelligence", "#attachmentstyles", "#selfawareness", "#mentalwellness", "#boundaries"],
    "competitor_accounts": [],
    "discovery_hashtags": ["#attachmenttheory", "#anxietytips", "#peoplepleasing", "#emotionalregulation", "#traumarecovery"],
    "citation_style": "academic_doi",
    "citation_source_types": ["clinical psychology journals", "neuroscience research", "mental health clinical trials"],
    "carousel_cta_topic": "psychology",
    "carousel_cta_options": [
        {"text": "Follow @{account} to learn more about {cta_topic}", "weight": 34},
        {"text": "If you want science-backed mental health content, follow @{account}!", "weight": 33},
        {"text": "If you want to learn more about {cta_topic}, follow our page!", "weight": 33},
    ],
    "follow_section_text": "Follow @{account} for weekly psychology insights",
    "save_section_text": "Save this — read it again when you need perspective",
    "disclaimer_text": "This content is for educational purposes based on published psychological research. It is not a substitute for professional mental health treatment. If you are struggling, please reach out to a licensed therapist or mental health professional.",
    "yt_title_examples": [
        "The Attachment Style Test That Explains Your Relationships",
        "Why You Can't Stop People-Pleasing (A Psychologist Explains)",
        "The Anxiety Trick Your Brain Plays on You (Neuroscience Breakdown)",
        "How Narcissists Manipulate You — 7 Tactics Backed by Research",
        "The Boundary-Setting Script Therapists Actually Recommend",
        "Why Smart People Struggle With Self-Esteem (The Imposter Cycle)",
        "I Tried Every Therapy Method for 1 Year — Here's What Worked"
    ],
    "yt_title_bad_examples": [
        "Mental Health Tips",
        "How to Be Happier",
        "Understanding Anxiety",
        "Psychology Facts",
        "Self-Care Advice"
    ]
}
