"""Template 5: Cooking & Quick Recipes"""

TEMPLATE_DATA = {
    "template_name": "cooking-quick-recipes",
    "template_category": "niche",
    "is_active": True,
    "popularity_order": 5,
    "name": "Cooking & Quick Recipes",
    "description": "Food science meets home cooking. Quick recipes, technique tips, and the science behind why recipes work.",
    "niche_name": "Cooking & Quick Recipes",
    "niche_description": "Home cooking education combining quick recipes with food science explanations. Understanding WHY techniques work makes you a better cook than following recipes blindly.",
    "content_brief": "Food science meets practical cooking content for home cooks aged 22–45 in English-speaking countries (US, UK, Canada, Australia), focusing on the 'why' behind cooking techniques, not just the 'how.' Topics include: the Maillard reaction and why proper searing transforms flavor, salt science and when to season at each cooking stage, knife skills that save 30 minutes per meal prep, the food science behind why restaurant food tastes better (butter, acid, umami layering), mise en place as a system (not just a fancy term), temperature control mastery (why low-and-slow vs high-heat produce completely different results), emulsion science for perfect sauces and dressings, the 5 mother sauces simplified for home cooks, meal prep strategies that don't result in sad repetitive lunches, substitution science (what you can swap and why it works chemically), common cooking mistakes ranked by impact (overcrowding the pan, not preheating, under-seasoning), flavor balancing with the sweet-salty-sour-bitter-umami framework, and batch cooking strategies for busy professionals. Tone is like a passionate home cook who also happens to love food science — enthusiastic, practical, and slightly nerdy about the chemistry of deliciousness. Uses specific temperatures, ratios, timing, and food science explanations rather than vague instructions. The style is revelation-driven — every post should make someone say 'so THAT'S why my food doesn't taste like a restaurant.' Content philosophy: cooking is applied chemistry. Understanding the science behind techniques makes you a better cook than memorizing a thousand recipes.",
    "target_audience": "22-45 year-olds who cook at home, US/UK/Canada/Australia",
    "audience_description": "Home cooks ranging from beginners to intermediate who want to level up their cooking. They follow food content on Instagram and TikTok, save recipes, and want to understand technique — not just follow steps.",
    "content_tone": ["enthusiastic", "educational", "encouraging", "science-curious", "practical"],
    "tone_avoid": ["pretentious", "gatekeeping", "overly complicated", "food shaming"],
    "topic_categories": ["Technique", "Food Science", "Quick Recipes", "Meal Prep", "Kitchen Tools", "Flavor Building", "Common Mistakes", "Restaurant Secrets"],
    "topic_keywords": ["Maillard reaction", "mise en place", "seasoning", "knife skills", "meal prep", "one pot meals", "food science", "flavor compounds", "cooking temperature", "rest time"],
    "topic_avoid": ["extreme diets", "food fear mongering", "raw food pseudoscience", "fake restaurant drama"],
    "content_philosophy": "Great cooking is understanding WHY, not just WHAT. When you understand the Maillard reaction, you never burn food again. When you understand salt science, every dish tastes better. We teach the principles, not just the recipes.",
    "hook_themes": ["mistakes ruining your cooking", "restaurant secrets for home cooks", "food science that changes everything", "the technique nobody taught you", "why your food doesn't taste like a restaurant"],
    "reel_examples": [
        {"title": "WHY YOUR STEAK NEEDS TO REST (THE SCIENCE)", "content_lines": ["You just cooked the perfect steak", "DON'T cut it yet", "During cooking, juices move to the center", "If you cut immediately, they pour onto the plate", "Resting for 5-10 minutes redistributes the juice", "Result: 38% more moisture in every bite", "Rest time = roughly half the cooking time"]},
        {"title": "YOU'RE USING SALT WRONG", "content_lines": ["Salt isn't just about making food salty", "It suppresses bitterness and enhances sweetness", "Salt your pasta water like the ocean (1 tbsp per liter)", "Season meat 45 minutes before cooking (or right before)", "Never salt between 5-44 minutes — worst of both worlds", "Finish with flaky salt for texture contrast", "Salt is a flavor amplifier, not a flavor"]},
        {"title": "CRISPY CHICKEN SKIN IN ONE STEP", "content_lines": ["Want restaurant-level crispy chicken skin?", "Pat it dry. That's it. That's the secret.", "Moisture is the enemy of crispiness", "Dry skin + hot oil = Maillard reaction = crispy", "Wet skin = steam = soggy", "Pat dry with paper towels. Season. High heat.", "The best technique is also the simplest"]},
        {"title": "THE PASTA MISTAKE 90% OF HOME COOKS MAKE", "content_lines": ["You're draining all your pasta water", "That starchy water is LIQUID GOLD", "It emulsifies your sauce — makes it creamy and clingy", "Save 1 cup before draining", "Add pasta directly to the sauce pan", "Splash in pasta water and toss vigorously", "The starch binds everything together. Restaurant-level pasta."]},
        {"title": "WHY RESTAURANT FOOD TASTES BETTER (3 SECRETS)", "content_lines": ["Secret 1: They use WAY more butter than you think", "Secret 2: They season at EVERY stage, not just at the end", "Secret 3: They cook on higher heat with better pans", "Also: they rest their meat, deglaze their pans", "And finish with acid (lemon, vinegar) for brightness", "Your food isn't bad — you're just underseasoning", "Be brave with salt, fat, acid, and heat"]},
        {"title": "STOP CROWDING YOUR PAN", "content_lines": ["This is the #1 reason your food isn't browning", "Crowding = steam instead of sear", "Food releases moisture when it hits heat", "A crowded pan traps that moisture — creating steam", "Leave 1-2 inches between pieces", "Cook in batches if needed", "Golden brown = flavor. Pale and soggy = too much food in the pan."]},
        {"title": "THE 5-INGREDIENT DINNER FORMULA", "content_lines": ["Every great quick dinner has these 5 elements:", "1. Protein (chicken, tofu, eggs, beans)", "2. Starch (rice, pasta, bread, potatoes)", "3. Vegetable (whatever you have)", "4. Fat (olive oil, butter, sesame oil)", "5. Acid (lemon, vinegar, tomato)", "Master this formula, never follow a recipe again"]},
        {"title": "HOW TO SHARPEN YOUR KNIFE (IT'S EASIER THAN YOU THINK)", "content_lines": ["A dull knife is the most dangerous tool in your kitchen", "It slips off food and cuts YOU instead", "Honing rod: use it every time you cook (realigns the edge)", "Whetstone: use it monthly (actually sharpens)", "20-degree angle, 5-10 strokes per side", "Test: if it slides through a tomato skin, it's sharp", "Sharp knife = safer, faster, more enjoyable cooking"]},
        {"title": "GARLIC: THE TIMING SECRET CHEFS KNOW", "content_lines": ["Add garlic first = burnt and bitter (it cooks in 30 seconds)", "The right way:", "Sauté your aromatics (onion, celery, carrot) first", "Add garlic in the LAST 30-60 seconds", "Just until fragrant — never brown", "Burnt garlic ruins an entire dish", "This one fix will transform your cooking"]},
        {"title": "THE MAILLARD REACTION EXPLAINED IN 45 SECONDS", "content_lines": ["That golden-brown crust on your steak? Maillard reaction.", "The crispy edge of a grilled cheese? Maillard.", "It's not caramelization — that's only sugar", "Maillard = amino acids + sugars + high heat (280°F+)", "Creates hundreds of new flavor compounds", "Requirements: dry surface, high heat, patience", "This one reaction is responsible for most 'delicious' flavors"]}
    ],
    "post_examples": [
        {"title": "THE SCIENCE OF PERFECT RICE EVERY TIME", "slides": ["Rice seems simple, but more people mess it up than almost any other staple. Whether it's mushy, crunchy, or stuck to the pot — the fix is understanding the science of starch and water absorption.", "The ratio myth: '2 cups water to 1 cup rice' works for some types but not all. Basmati: 1.5:1 water ratio. Jasmine: 1.25:1. Short grain: 1:1. The grain length determines how much starch is present and how much water it absorbs.", "The technique that never fails: Rinse rice until water runs clear (removes surface starch = less sticky). Toast in oil for 1 minute (adds nutty flavor). Add correct water ratio. Bring to boil, then reduce to lowest heat. Cover. Set timer. NEVER LIFT THE LID. Rest 10 minutes off heat.", "The food science: Rice gelatinizes at 150°F — starch granules absorb water and swell. If you add too much water, granules burst (mushy). Too little, and the center stays crunchy. Resting redistributes moisture evenly. Understanding this means you never need a rice cooker."], "study_ref": "Food Chemistry, 2020 — Starch Gelatinization in Rice Varieties"},
        {"title": "WHY YOUR SCRAMBLED EGGS ARE RUBBERY", "slides": ["Gordon Ramsay's scrambled eggs look like silk. Yours look like rubber. The difference isn't skill — it's temperature and timing. Here's the food science that fixes everything.", "Eggs are 75% water and 13% protein. When heated, proteins unfold and bond together (coagulation). At 160°F, they set softly. At 180°F+, they squeeze out water and become rubbery. The enemy: too much heat.", "The technique: Cold butter in a cold pan. Add beaten eggs. Turn heat to LOW. Stir constantly with a spatula, on and off the heat. Total cooking time: 4-5 minutes. Remove from heat BEFORE they look done — carryover cooking finishes them.", "The science of additions: Salt before cooking = smoother texture (weakens protein bonds). Cream cheese at the end = creamy richness that stops cooking. Never add milk before cooking (dilutes eggs without improving texture). Butter > oil (adds flavor AND emulsifies)."], "study_ref": "Journal of Food Science, 2019 — Thermal Denaturation of Egg Proteins"},
        {"title": "MEAL PREP: THE EVIDENCE-BASED APPROACH", "slides": ["A Cambridge study found that people who meal prep eat 25% more vegetables and save $1,200/year on food. Yet most people quit within 3 weeks because they overcomplicate it.", "The batch-component method (not full meals): Cook 2 proteins, 2 grains, 3 vegetables on Sunday. Mix and match throughout the week. This prevents 'meal prep fatigue' — eating the same container for 5 days straight.", "Storage science matters: Cooked chicken lasts 3-4 days refrigerated. Rice is safe for 3 days max (Bacillus cereus risk after). Roasted vegetables last 5 days. Sauces and dressings stored separately last longest. Glass containers > plastic for reheating.", "The 90-minute Sunday prep: 0-20min: Season and start proteins in oven. 20-40min: Cook grains on stovetop, chop vegetables. 40-60min: Roast vegetables, make 1-2 sauces. 60-90min: Cool, portion, store. Done for the week."], "study_ref": "International Journal of Behavioral Nutrition, 2021 — Meal Preparation and Diet Quality"},
        {"title": "THE FLAVOR BUILDING BLOCKS EVERY COOK SHOULD KNOW", "slides": ["Professional chefs don't follow recipes — they understand the 5 elements of flavor and balance them intuitively. Once you learn this framework, you can fix any dish and create your own recipes.", "The 5 elements: Salt (enhances all other flavors), Fat (carries flavor and adds richness), Acid (brightness and balance — lemon, vinegar, tomato), Heat (spice, not temperature — chili, pepper, ginger), Sweet (balance bitterness and acidity — sugar, honey, caramelized onions).", "The fixing framework: Dish tastes flat? Add salt. Too rich/heavy? Add acid. Too sour/sharp? Add fat or sweet. Too spicy? Add fat or acid. Bitter? Add salt or sweet. Samin Nosrat's Salt Fat Acid Heat framework is backed by food chemistry — these interactions are measurable.", "Practice exercise: Make a simple vinaigrette. Start with 3:1 oil to acid. Taste. Add salt — notice how the acid mellows. Add honey — notice how it rounds out. Add chili flakes — notice the complexity. You just learned to balance all 5 elements in 2 minutes."], "study_ref": "Samin Nosrat, Salt Fat Acid Heat + Food Chemistry Research, 2023"},
        {"title": "KNIFE SKILLS: THE FOUNDATION OF FASTER COOKING", "slides": ["Professional chefs spend their first year mastering knife skills. Not because it's tradition — because proper technique cuts prep time by 60% and makes food cook more evenly.", "The 3 essential cuts: Dice (uniform cubes — ensures even cooking), Julienne (thin matchsticks — for stir-fries and garnishes), Chiffonade (thin ribbons — for herbs and leafy greens). Master these three and you can handle 90% of all prep work.", "The claw grip is non-negotiable: Curl your fingertips under, with knuckles guiding the blade. This is how chefs cut fast without cutting themselves. The blade should touch your knuckles, never pass them. A University hospital study found 80% of kitchen cuts come from improper grip.", "Speed comes from consistency, not rushing: Use a rocking motion (keep the tip on the board). Let the weight of the knife do the work — don't press down hard. Practice uniform cuts on an onion daily for one week. By day 7, your prep speed will double."], "study_ref": "Culinary Institute of America Technical Standards + British Medical Journal Kitchen Injury Study, 2021"},
        {"title": "THE SCIENCE OF CARAMELIZATION VS MAILLARD", "slides": ["These two reactions are responsible for 90% of 'delicious' flavors, yet most people confuse them. Understanding the difference makes you a fundamentally better cook.", "Caramelization: Only involves SUGAR. Occurs at 320°F+. Sugar molecules break down and recombine into hundreds of new flavor compounds (butterscotch, toffee, nuttiness). Think: crème brûlée, caramelized onions, roasted sweet potatoes.", "Maillard Reaction: Involves PROTEIN + SUGAR together. Occurs at 280°F+. Creates entirely different flavor compounds than caramelization. Think: seared steak, toasted bread, roasted coffee, golden-brown cookies. This is the reaction behind most 'umami' flavors.", "Practical application: For Maillard (protein browning): Dry the surface, high heat, don't crowd the pan. For caramelization (sugar browning): Low and slow, stir occasionally, be patient. Caramelized onions take 45 minutes — anything less is just softened onions."], "study_ref": "Journal of Agricultural and Food Chemistry, 2022 — Maillard Reaction Products Review"},
        {"title": "FOOD SAFETY MYTHS DEBUNKED", "slides": ["The 5-second rule, washing chicken, and 'if it smells fine it's safe' — food safety myths cause 48 million illnesses annually in the US alone. Here's what the science actually says.", "Myth 1: The 5-second rule. A Rutgers study found bacteria transfers to food in under 1 second. Wet foods pick up more bacteria than dry foods, but ALL dropped food is contaminated immediately. Myth 2: Wash raw chicken. The USDA explicitly says DON'T — it splashes bacteria up to 3 feet across your kitchen.", "Myth 3: If it doesn't smell bad, it's safe. Pathogenic bacteria (Salmonella, E. coli, Listeria) are odorless. By the time food smells 'off,' it has millions of bacteria — but it was dangerous long before that. Trust dates and temperature, not your nose.", "The temperature rules: Danger zone: 40-140°F (bacteria double every 20 minutes). Refrigerate leftovers within 2 hours (1 hour if above 90°F). Reheat to 165°F internal temp. Thaw in the fridge, NEVER on the counter. Use a food thermometer — it's the single most important kitchen safety tool."], "study_ref": "Rutgers University Food Science, 2020 + CDC Foodborne Illness Data"},
        {"title": "ONE-POT COOKING: WHY IT WORKS AND HOW TO MASTER IT", "slides": ["One-pot meals aren't just lazy cooking — they're flavor science at work. Every ingredient contributes to a shared cooking liquid that concentrates and melds flavors over time.", "The layering principle: Build flavor in stages. 1) Brown protein (Maillard flavors). 2) Sauté aromatics (onion, garlic, ginger). 3) Deglaze (wine, stock, tomatoes lift fond from the pan). 4) Add liquids and slow-cook ingredients. Each layer compounds on the previous one.", "The science of braising: Low, slow cooking (300°F, 2+ hours) breaks down collagen in tough cuts into gelatin. This creates the rich, silky body of stews and braises. Cheap cuts (chuck, shoulder, thigh) outperform expensive cuts in one-pot cooking because they have MORE collagen.", "5 one-pot templates: 1) Protein + tomatoes + beans + spices = chili. 2) Protein + curry paste + coconut milk + vegetables = curry. 3) Protein + stock + grain + vegetables = risotto/pilaf. 4) Protein + pasta + cream/tomato sauce = pasta bake. 5) Eggs + vegetables + cheese = frittata. Master the templates, vary the ingredients."], "study_ref": "The Food Lab, J. Kenji López-Alt + Journal of Texture Studies, 2021"},
        {"title": "SPICE BLOOMING: THE 30-SECOND TRICK THAT CHANGES EVERYTHING", "slides": ["Raw spices are like untuned instruments — they have potential but sound flat. Blooming spices in fat for 30 seconds releases volatile flavor compounds that make everything taste 3x better.", "The science: Spice flavor compounds are mostly fat-soluble, not water-soluble. When you heat spices in oil or butter, the fat extracts and distributes these compounds throughout the entire dish. Adding dry spices to liquid traps them in undissolved clumps.", "The technique: Heat oil/butter in your pan over medium heat. Add whole spices (cumin seeds, mustard seeds, cinnamon sticks) for 30-45 seconds until fragrant and sizzling. For ground spices, add them for 15-20 seconds only — they burn faster. Then add your other ingredients.", "Where to use this: Every curry (bloom spices before adding onions). Every soup (bloom garlic and spices in olive oil). Every grain dish (toast spices before adding rice/quinoa). Every stir-fry (bloom aromatics in oil first). This single technique elevates home cooking more than any tool or gadget."], "study_ref": "Journal of Food Science, 2022 — Thermal Release of Volatile Spice Compounds"},
        {"title": "THE COMPLETE GUIDE TO COOKING OILS", "slides": ["Not all oils are created equal, and using the wrong one can ruin your dish or create harmful compounds. Here's the science-based guide to choosing the right oil for every cooking method.", "Smoke point matters: When oil reaches its smoke point, it breaks down, releases acrid flavors, and forms harmful free radicals. High-heat cooking (searing, frying): Avocado oil (520°F), refined olive oil (465°F), ghee (485°F). Medium heat: Extra virgin olive oil (375°F), butter (350°F). No heat: walnut, flaxseed, sesame (finishing oils).", "The extra virgin olive oil debate: Despite its lower smoke point, a 2018 Australian study found EVOO is actually stable at high cooking temperatures because of its high antioxidant content. It produces fewer harmful compounds than canola or sunflower oil when heated. The smoke point alone doesn't tell the whole story.", "Storage and freshness: Oil goes rancid (oxidizes) when exposed to light, heat, and air. Store in dark glass bottles, away from the stove. Smell before using — rancid oil smells like crayons or old nuts. Replace oils every 3-6 months. Buy smaller bottles more often rather than bulk sizes."], "study_ref": "ACTA Scientific Nutritional Health, 2018 — Evaluation of Chemical and Physical Changes in Cooking Oils"}
    ],
    "image_style_description": "Warm, appetizing food photography aesthetic. Rich amber/brown tones with pops of fresh green. Overhead shots, step-by-step visuals, ingredient grids.",
    "image_palette_keywords": ["warm amber", "rich brown", "fresh green", "appetizing", "rustic", "natural"],
    "brand_personality": "Your scientifically curious home cook friend who explains the 'why' behind every recipe. Makes food science feel like a fun discovery, not a lecture.",
    "brand_focus_areas": ["cooking techniques", "food science", "quick recipes", "meal prep", "flavor building"],
    "parent_brand_name": "",
    "cta_options": [
        {"text": "Follow for cooking tips that actually make a difference", "weight": 30},
        {"text": "Save this recipe for dinner tonight", "weight": 25},
        {"text": "Share with someone learning to cook", "weight": 20},
        {"text": "Follow for more food science and recipes", "weight": 25}
    ],
    "hashtags": ["#cooking", "#recipes", "#foodscience", "#homecooking", "#cookingtips", "#easyrecipes", "#mealprep"],
    "competitor_accounts": [],
    "discovery_hashtags": ["#cookinghacks", "#kitchentips", "#foodie", "#homechef", "#quickrecipes"],
    "citation_style": "informal",
    "citation_source_types": ["food science journals", "USDA research", "culinary institute studies"],
    "carousel_cta_topic": "cooking and food science",
    "carousel_cta_options": [
        {"text": "Save this cooking breakdown", "weight": 40},
        {"text": "Tag someone who needs this in the kitchen", "weight": 30},
        {"text": "Follow for weekly cooking science", "weight": 30}
    ],
    "follow_section_text": "Follow @{account} for the science behind great cooking",
    "save_section_text": "Save this — you'll want it next time you're in the kitchen",
    "disclaimer_text": "Always follow food safety guidelines. Cooking temperatures and times are guidelines — use a food thermometer for accuracy.",
    "yt_title_examples": [
        "The Cooking Mistake That Ruins 90% of Home Meals (Chefs Never Do This)",
        "Why Restaurant Steak Tastes Better — The 3 Secrets They Don't Tell You",
        "I Tested Every Pasta Cooking Method — The Winner Surprised Me",
        "The Science of Salt: When to Season Changes EVERYTHING",
        "5 Knife Skills That Cut Your Prep Time in Half",
        "Why Your Garlic Always Burns (And the 10-Second Fix)",
        "The $3 Ingredient That Makes Everything Taste Like a Restaurant"
    ],
    "yt_title_bad_examples": [
        "Cooking Tips for Beginners",
        "Easy Dinner Recipes",
        "How to Cook Better",
        "Kitchen Hacks",
        "Quick and Easy Meals"
    ]
}
