"""Template 7: Tech & Productivity"""

TEMPLATE_DATA = {
    "template_name": "tech-productivity",
    "template_category": "niche",
    "is_active": True,
    "popularity_order": 7,
    "name": "Tech & Productivity",
    "description": "Technology tools, AI workflows, and productivity systems that help you work smarter and live better in the digital age.",
    "niche_name": "Tech & Productivity",
    "niche_description": "Technology and productivity education covering AI tools, digital workflows, app recommendations, and systems thinking for getting more done with less effort.",
    "content_brief": "Practical technology and productivity systems content for professionals and knowledge workers aged 22–40 in English-speaking countries (US, UK, Canada, Australia), focusing on leveraging technology and systems thinking for maximum output with minimum friction. Topics include: AI tools that actually save time vs AI hype (with specific before/after workflow comparisons), second brain methodology (Zettelkasten, PARA, building a personal knowledge management system), time blocking science and why it outperforms todo lists (Cal Newport's deep work research), app workflows that automate repetitive tasks (Zapier/Make chains, Shortcuts, Alfred workflows), digital minimalism and the attention economy (how to reclaim focus in a notification-driven world), the note-taking stack that replaced 5 apps (specific tool recommendations with migration guides), keyboard shortcuts that save 30+ hours per year (calculated), email management systems (Inbox Zero vs batch processing, the research behind each), meeting optimization (async-first culture, when meetings are actually worth it), the Pomodoro technique evolution (what modern research says about work-rest ratios), setting up a development environment or creative workspace for flow, browser extension stacks for research and writing, file organization systems that scale, and automation scripts for common tasks. Tone is like a tech-savvy colleague who actually tests every tool before recommending it — enthusiastic about what works, critical about what's overhyped, and focused on real productivity gains. Uses specific time savings, step-by-step setups, and before/after comparisons rather than vague 'work smarter' advice. The style is systems-oriented and practical — every post should be implementable in under 30 minutes. Content philosophy: productivity is about designing systems, not exercising willpower. The right tools and workflows should make the right behavior the easy behavior.",
    "target_audience": "22-40 knowledge workers and tech enthusiasts, US/UK/Canada/Australia",
    "audience_description": "Knowledge workers, freelancers, and tech-curious professionals who want to leverage technology for productivity. They try new apps, follow tech trends, and want systems — not just tools.",
    "content_tone": ["practical", "forward-thinking", "analytical", "tool-focused", "efficient"],
    "tone_avoid": ["technophobia", "AI doomsday", "overly technical jargon", "tool worship without substance"],
    "topic_categories": ["AI Tools", "Productivity Systems", "Apps & Software", "Digital Organization", "Automation", "Time Management", "Note-Taking", "Remote Work"],
    "topic_keywords": ["AI tools", "ChatGPT", "Notion", "second brain", "time blocking", "automation", "Zapier", "digital minimalism", "deep work", "keyboard shortcuts"],
    "topic_avoid": ["piracy tools", "surveillance software", "get-rich-quick AI schemes", "crypto trading bots"],
    "content_philosophy": "Technology should simplify your life, not complicate it. The best productivity system is the one you actually use. We focus on the 20% of tools and techniques that deliver 80% of results — and we're honest about what's hype and what actually works.",
    "hook_themes": ["AI tools that save hours weekly", "the productivity system you're missing", "apps that replaced my entire workflow", "tech tips most people don't know", "why you're using this tool wrong"],
    "reel_examples": [
        {"title": "5 AI TOOLS THAT REPLACED MY ENTIRE TEAM", "content_lines": ["Writing: Claude/ChatGPT saves 10+ hours/week on first drafts", "Design: Canva AI generates social media graphics in seconds", "Meetings: Otter.ai transcribes and summarizes every call", "Research: Perplexity AI replaces hours of Googling", "Scheduling: Calendly + Zapier automates my booking flow", "Total time saved: ~20 hours per week", "Total cost: less than $100/month"]},
        {"title": "THE SECOND BRAIN METHOD IN 60 SECONDS", "content_lines": ["Your brain is for having ideas, not storing them", "Capture everything in ONE place (Notion, Obsidian, Apple Notes)", "Organize by project, not by topic", "Review weekly — connect dots between notes", "When you need something, search — don't remember", "This system is called 'Building a Second Brain'", "It works because it matches how your brain naturally processes"]},
        {"title": "STOP CHECKING EMAIL FIRST THING IN THE MORNING", "content_lines": ["Email puts you in reactive mode", "You start solving OTHER people's priorities", "Instead: block your first 2 hours for deep work", "No email, no Slack, no notifications", "Cal Newport calls this 'time blocking'", "A UC Irvine study: it takes 23 minutes to refocus after an interruption", "Protect your morning brain. It's your most valuable resource."]},
        {"title": "KEYBOARD SHORTCUTS THAT SAVE 100+ HOURS A YEAR", "content_lines": ["Ctrl+Shift+T: reopen last closed tab (life-changing)", "Win+V: clipboard history (copy MULTIPLE things)", "Ctrl+L: jump to URL bar instantly", "Ctrl+Shift+N: incognito window in 1 second", "Alt+Tab: switch between apps instantly", "These 5 shortcuts save ~30 minutes daily", "That's 182 hours per year. You're welcome."]},
        {"title": "YOUR PHONE IS MAKING YOU DUMBER (THE DATA)", "content_lines": ["A University of Texas study put phones in 3 positions:", "On desk, in pocket, in another room", "Cognitive performance was WORST with phone on desk", "Even face-down, turned off", "Your brain uses energy resisting the urge to check", "It's called 'brain drain' — the phone's PRESENCE reduces IQ", "Put your phone in another room during focused work"]},
        {"title": "THE NOTE-TAKING APP THAT CHANGED MY LIFE", "content_lines": ["I tried Evernote, Notion, Bear, Apple Notes, Roam", "The winner: Obsidian (and here's why)", "Your notes are stored as plain text files — YOU own them", "Backlinks connect ideas like a web (not folders)", "It works offline — no internet needed", "Free for personal use", "But honestly? The best app is the one you'll actually use"]},
        {"title": "HOW I AUTOMATE 50% OF MY WORK", "content_lines": ["Email filters sort 90% of incoming mail automatically", "Zapier connects my apps: form → spreadsheet → email", "TextExpander: type 'addr' → full address in 1 second", "Calendar blocks: recurring focus time blocks automatically", "Templates: every meeting has a pre-built agenda template", "Automation isn't about being lazy", "It's about spending energy on work that matters"]},
        {"title": "THE POMODORO TECHNIQUE IS OVERRATED (DO THIS INSTEAD)", "content_lines": ["25-minute work blocks are too short for deep work", "By the time you're in flow, the timer rings", "Instead: use 90-minute focus blocks", "This matches your brain's ultradian rhythm", "90 minutes of deep work, 20-minute break", "No phone, no notifications during the block", "3 blocks per day = more output than most people do in a week"]},
        {"title": "NOTION SETUP THAT RUNS MY ENTIRE LIFE", "content_lines": ["One dashboard for everything:", "Tasks: kanban board with priorities and deadlines", "Notes: linked database with tags and search", "Habits: daily tracker with streak counter", "Goals: quarterly OKRs with progress bars", "Content: editorial calendar for all platforms", "Setup took 2 hours. Saves me 10 hours/week.", "Template link in bio (it's free)"]},
        {"title": "AI PROMPTS THAT 10X YOUR OUTPUT", "content_lines": ["Bad prompt: 'Write me a blog post'", "Good prompt: 'Write a 500-word blog post about [topic] for [audience], using a [tone] voice, structured with headers and bullet points'", "The difference: specificity", "Always include: role, context, format, length, tone", "AI isn't replacing you — it's amplifying you", "The person who knows how to prompt well", "Outperforms the one who knows the subject better"]}
    ],
    "post_examples": [
        {"title": "THE COMPLETE AI TOOLS STACK FOR 2026", "slides": ["AI tools have gone from novelty to necessity in under 3 years. But with hundreds of options, most people are either overwhelmed or using the wrong tools. Here's the curated stack that actually delivers ROI for knowledge workers.", "Writing & Research: ChatGPT/Claude for first drafts and brainstorming, Perplexity for research with citations, Grammarly for editing (catches tone issues, not just grammar), Otter.ai for meeting transcription and summaries. Combined time savings: 10-15 hours/week.", "Visual & Creative: Midjourney/DALL-E for concept imagery, Canva AI for quick social graphics and presentations, Descript for video editing (text-based), Eleven Labs for voiceovers. These tools don't replace creativity — they remove the technical friction.", "Automation & Productivity: Zapier/Make for connecting apps without code, Raycast/Alfred for Mac command-line productivity, Superhuman for email (AI triage, quick replies), Motion for AI-powered calendar scheduling. The key: invest 2 hours setting up each tool properly. Poor setup = poor results."], "study_ref": "McKinsey AI Adoption Survey, 2025 — Productivity Impact of AI Tools"},
        {"title": "THE SECOND BRAIN METHOD: A COMPLETE GUIDE", "slides": ["Tiago Forte's 'Building a Second Brain' methodology has been adopted by over 100,000 knowledge workers. The premise: your brain is for having ideas, not storing them. Offload everything into a trusted system.", "The PARA method organizes everything into 4 categories: Projects (active, with deadlines), Areas (ongoing responsibilities), Resources (reference material), Archive (completed/inactive). Every piece of information goes into exactly ONE of these. No 'miscellaneous' folder.", "The progressive summarization technique: When you capture a note, bold the key passages. Later, highlight the bolded passages. Later still, create a brief executive summary. Each layer makes retrieval faster. You're building a distilled knowledge base, not a note graveyard.", "Getting started in 30 minutes: 1) Pick ONE app (Notion, Obsidian, or Apple Notes). 2) Create 4 folders: Projects, Areas, Resources, Archive. 3) Move your next 3 active projects into 'Projects.' 4) For one week, capture every interesting idea/article into 'Resources.' 5) Review weekly. The system compounds over time."], "study_ref": "Tiago Forte, Building a Second Brain + Ebbinghaus Forgetting Curve Research"},
        {"title": "DEEP WORK: THE COMPLETE PRODUCTIVITY FRAMEWORK", "slides": ["Cal Newport's 'Deep Work' research found that the ability to focus without distraction is becoming the most valuable skill of the 21st century — while simultaneously becoming the rarest. Here's how to reclaim it.", "The data is stark: Knowledge workers are interrupted every 11 minutes on average. It takes 23 minutes to regain full focus after an interruption. That means most people NEVER reach deep focus during a typical workday. Email, Slack, and phone notifications are productivity's biggest enemies.", "The 4 Deep Work strategies: 1) Monastic: eliminate all shallow work (unrealistic for most). 2) Bimodal: dedicate full days to deep work, other days to meetings/email. 3) Rhythmic: same time block every day for deep work (most sustainable). 4) Journalistic: fit deep work into any available gap (requires practice).", "The implementation protocol: 1) Choose your strategy (rhythmic works for 80% of people). 2) Block 2-4 hours daily for deep work in your calendar. 3) During deep work: phone in another room, notifications OFF, door closed. 4) Track deep work hours weekly — aim for 3-4 hours/day minimum. 5) You'll produce more meaningful output in 4 focused hours than 8 distracted ones."], "study_ref": "Cal Newport, Deep Work + University of California Irvine Interruption Study, 2023"},
        {"title": "NOTION VS OBSIDIAN VS ROAM: THE HONEST COMPARISON", "slides": ["Three apps dominate the 'second brain' space, and the internet is full of biased reviews from creators with affiliate links. Here's the genuinely honest comparison based on what each tool does best — and worst.", "Notion: Best for teams, project management, and visual organization. Databases are powerful. Downsides: requires internet, slower search in large vaults, your data lives on their servers. Best for: project managers, teams, visual thinkers. Learning curve: moderate.", "Obsidian: Best for personal knowledge management, linking ideas, and data ownership. Plain markdown files stored locally — YOU own your data forever. Incredible plugin ecosystem. Downsides: steeper learning curve, less visual, collaboration requires paid sync. Best for: writers, researchers, privacy-focused users.", "Roam Research: Pioneer of bidirectional linking. Best for daily journaling and emergent thinking. Downsides: expensive ($15/month), smaller community, no offline mode, uncertain long-term viability. Verdict: For most people, Notion (visual/team) or Obsidian (personal/privacy) are the best choices. The winner is whichever you'll actually use daily."], "study_ref": "Product Hunt Analysis + r/PKMS Community Survey, 2025"},
        {"title": "THE SCIENCE OF TIME BLOCKING", "slides": ["Time blocking — assigning every hour a specific task — sounds rigid. But research shows it's the single most effective productivity technique, outperforming to-do lists, priority matrices, and Pomodoro combined.", "A 2023 study in the Journal of Applied Psychology found that workers who time-blocked their days completed 40% more high-priority tasks and reported 26% lower stress than those using traditional to-do lists. The key: time blocking reduces decision fatigue.", "The method: Sunday evening (15 minutes): review the week ahead and block 3-5 priorities. Each morning (5 minutes): confirm and adjust today's blocks. Categories: Deep Work (creative/analytical), Shallow Work (email/admin), Meetings, Personal. Color-code for visual clarity.", "Common pitfalls and fixes: 'My day is unpredictable' → Block only 60% of your day, leave 40% as buffer. 'I can't estimate task duration' → Double your estimates for the first month, then calibrate. 'Meetings destroy my blocks' → Batch meetings into 1-2 days (Meeting Mondays/Thursdays). The goal isn't rigidity — it's intentionality."], "study_ref": "Journal of Applied Psychology, 2023 — Time Blocking and Task Completion"},
        {"title": "DIGITAL MINIMALISM: RECLAIMING YOUR ATTENTION", "slides": ["The average person checks their phone 144 times per day and spends 4.5 hours on it. Cal Newport's digital minimalism philosophy argues that most of this time is spent on things we wouldn't consciously choose. The cost: our attention, creativity, and mental health.", "The 30-day digital declutter: Remove all optional technology from your life for 30 days. No social media, no news apps, no streaming (keep essential communication and work tools). During these 30 days, rediscover what you actually enjoy and value.", "After 30 days, slowly reintroduce only technology that serves something you deeply value. Apply the 'access vs. ownership' test: you can ACCESS social media from a browser on your laptop — you don't need the app ON your phone. This friction is the point.", "The ongoing maintenance: Phone grayscale mode (reduces dopamine-driven scrolling by 38%). App usage limits (Screen Time/Digital Wellbeing). No phone in bedroom. One-in-one-out rule for new apps. The goal isn't zero technology — it's intentional technology that serves your values instead of exploiting your attention."], "study_ref": "Cal Newport, Digital Minimalism + Common Sense Media Screen Time Report, 2024"},
        {"title": "AUTOMATION FOR NON-DEVELOPERS: THE BEGINNER GUIDE", "slides": ["You don't need to code to automate 50% of your repetitive work. No-code automation tools like Zapier, Make, and Apple Shortcuts can handle tasks that currently eat hours of your week.", "The automation audit: Track your work for one week. Identify every task that is: repetitive (done more than 2x/week), rule-based (follows the same steps), digital (involves apps/data). Common automatable tasks: email sorting, data entry, meeting scheduling, invoice generation, social media posting, file organization.", "The beginner stack: Zapier/Make ($0-20/month) — connects apps (when X happens in app A, do Y in app B). TextExpander ($3/month) — type shortcuts that expand to full paragraphs, addresses, email templates. IFTTT (free) — simple if/then automations between apps and smart devices.", "Start with these 5 automations: 1) Auto-save email attachments to Google Drive. 2) Send a Slack message when a form is submitted. 3) Add meeting notes to a shared doc automatically. 4) Create tasks from starred emails. 5) Auto-post content across social platforms. Each takes 10-15 minutes to set up and saves hours weekly."], "study_ref": "Zapier State of Business Automation Report, 2025"},
        {"title": "THE PERFECT MORNING ROUTINE (BACKED BY CHRONOBIOLOGY)", "slides": ["Morning routines are everywhere on social media, but most ignore the science of chronobiology — your body's internal clock. The optimal routine depends on your chronotype, not some influencer's schedule.", "The 4 chronotypes (Dr. Michael Breus): Lion (early bird, 15% of population — peak hours 6am-noon), Bear (most common, 55% — peak hours 10am-2pm), Wolf (night owl, 15% — peak hours 5pm-midnight), Dolphin (light sleeper, 10% — peak varies). Your chronotype determines your ideal wake time, work hours, and exercise timing.", "The evidence-based morning elements (adjust timing to your chronotype): 1) Sunlight exposure within 30 minutes of waking (resets circadian rhythm — Huberman Lab research). 2) Delay caffeine 90-120 minutes after waking (cortisol is already high). 3) Movement before screens (even 10 minutes). 4) One priority task before email.", "The anti-routine principle: Rigid 5am routines fail for 85% of people because they fight their biology. Instead: identify your chronotype (free quiz at thepowerofwhenquiz.com), protect your peak hours for deep work, and design a flexible morning that respects your natural rhythm. Consistency of sleep/wake timing matters more than the specific time."], "study_ref": "Dr. Michael Breus, The Power of When + Huberman Lab Podcast, 2024"},
        {"title": "EMAIL MANAGEMENT: INBOX ZERO IN 30 MINUTES", "slides": ["The average knowledge worker spends 28% of their workday on email — 2.6 hours daily. That's 650 hours per year. Inbox Zero isn't about an empty inbox; it's about a decision-making system that eliminates email as a source of stress.", "The 4-D framework for every email: Delete (doesn't need action — 30% of emails), Delegate (someone else should handle this — forward with context), Defer (needs action but not now — move to a 'this week' folder), Do (takes less than 2 minutes — handle immediately).", "The batch processing protocol: Check email only 3 times daily (morning, post-lunch, end of day). Each session: 15-20 minutes maximum. Process every email using 4-D — never leave an email 'read but unprocessed.' Unsubscribe from 10 newsletters today — if you haven't read the last 3 issues, you won't read the next one.", "Email filters that do the work for you: Auto-label emails from your boss/VIPs. Auto-archive newsletters into a 'Read Later' folder. Auto-label CC'd emails (you're usually just FYI'd). Set up 3-5 templates for common responses. Use Superhuman, Shortwave, or Gmail keyboard shortcuts to process at 3x speed."], "study_ref": "McKinsey Global Institute — Email Productivity Study + Merlin Mann, Inbox Zero Methodology"},
        {"title": "THE ULTIMATE WORK-FROM-HOME PRODUCTIVITY SETUP", "slides": ["Remote workers who invest in their home office setup are 23% more productive than those working from their couch or kitchen table. The ROI of a proper setup pays for itself within months.", "The ergonomic essentials: External monitor at eye level (reduces neck strain 60%), Separate keyboard and mouse (prevents wrist issues), Chair with lumbar support (standing desk optional — alternating is best), Room with a door you can close (visual boundary = mental boundary).", "The digital setup: Two-screen workflow (reference on one, work on the other — saves 20% time switching). Noise-canceling headphones (even without music, they signal 'do not disturb'). Reliable webcam and microphone (your reputation in meetings depends on audio/video quality more than what you say).", "The productivity environment: Natural light from the side (reduces eye strain and boosts mood). Plants in your field of vision (a University of Exeter study found they improve productivity by 15%). No TV visible from your desk. Dedicated work space that you LEAVE at end of day — physical separation between work and life prevents burnout."], "study_ref": "Stanford Remote Work Study, 2024 + University of Exeter Office Plant Study"}
    ],
    "image_style_description": "Clean, modern tech aesthetic. Dark mode-inspired with electric blue and white accents. App screenshots, workflow diagrams, minimalist desk setups.",
    "image_palette_keywords": ["dark mode", "electric blue", "white", "clean", "modern", "tech"],
    "brand_personality": "Your tech-savvy productivity nerd who tests every tool so you don't have to. Practical, honest about what works and what's hype, and obsessed with saving time.",
    "brand_focus_areas": ["AI tools", "productivity systems", "digital organization", "time management", "automation"],
    "parent_brand_name": "",
    "cta_options": [
        {"text": "Follow for tech tips that save real time", "weight": 30},
        {"text": "Save this for your workflow upgrade", "weight": 25},
        {"text": "Share with someone who needs this", "weight": 20},
        {"text": "Follow for more productivity systems", "weight": 25}
    ],
    "hashtags": ["#productivity", "#techtools", "#AI", "#notion", "#deepwork", "#timemanagement", "#productivitytips"],
    "competitor_accounts": [],
    "discovery_hashtags": ["#secondbrain", "#digitalproductivity", "#AItools", "#worksmarter", "#remotewerk"],
    "citation_style": "informal",
    "citation_source_types": ["productivity research", "tech industry reports", "university studies"],
    "carousel_cta_topic": "tech and productivity",
    "carousel_cta_options": [
        {"text": "Save this tool breakdown", "weight": 40},
        {"text": "Share with your team", "weight": 30},
        {"text": "Follow for weekly productivity systems", "weight": 30}
    ],
    "follow_section_text": "Follow @{account} for tech tools and productivity systems that work",
    "save_section_text": "Save this — set it up this weekend",
    "disclaimer_text": "Tool recommendations are based on personal testing and research. Pricing and features may change. Always evaluate tools for your specific needs.",
    "yt_title_examples": [
        "The AI Tool That Replaced 5 Apps in My Workflow (Not ChatGPT)",
        "I Tested Every Productivity System for 30 Days — Clear Winner",
        "Why Your To-Do List Is Making You LESS Productive (Research Proves It)",
        "The 7 Keyboard Shortcuts That Save Me 2 Hours Every Day",
        "I Built a Second Brain — Here's What Changed After 6 Months",
        "Stop Using Email Wrong: The System That Cleared My Inbox Forever",
        "The $0 Automation Stack That Runs My Entire Business"
    ],
    "yt_title_bad_examples": [
        "Best Productivity Apps 2025",
        "How to Be More Productive",
        "Tech Tips and Tricks",
        "My Favorite Tools",
        "Productivity Advice"
    ]
}
