"""Template 3: Self-Improvement & Mindset"""

TEMPLATE_DATA = {
    "template_name": "self-improvement-mindset",
    "template_category": "niche",
    "is_active": True,
    "popularity_order": 3,
    "name": "Self-Improvement & Mindset",
    "description": "Evidence-based personal development, habit science, and cognitive psychology for ambitious people who want to level up their lives.",
    "niche_name": "Self-Improvement & Mindset",
    "niche_description": "Personal development rooted in behavioral science, cognitive psychology, and habit research. Moving beyond motivation quotes into actionable systems.",
    "content_brief": "Evidence-based self-improvement and mindset content for adults aged 20–40 in English-speaking countries (US, UK, Canada, Australia), bridging the gap between pop psychology and real behavioral science. Topics include: habit formation through the lens of neural pathway science (not just '21 days' myths), cognitive biases that sabotage decision-making (sunk cost, confirmation bias, Dunning-Kruger), dopamine management and why social media hijacks your motivation system, overthinking patterns and the rumination-anxiety loop, decision-making frameworks used by top performers (second-order thinking, inversion, pre-mortem analysis), the science of willpower depletion and how to design environments instead, emotional intelligence as a learnable skill with specific exercises, flow state triggers and how to engineer deep work sessions, the psychology of procrastination (it's emotional regulation, not laziness), stoic philosophy meets modern neuroscience, journaling protocols backed by expressive writing research, and morning routine science (what actually matters vs what's performative). Tone is a thoughtful mentor who reads research papers and explains them over coffee — intellectual but never pretentious, challenging but never condescending. Uses specific studies, frameworks, and actionable exercises rather than motivational platitudes. The style is myth-busting and deeply practical — content that changes how people think, not just how they feel. Content philosophy: real self-improvement is cognitive renovation, not motivational decoration. Every piece of content should give the viewer one mental model or technique they can apply today.",
    "target_audience": "20-40 year-olds ambitious professionals, US/UK/Canada/Australia",
    "audience_description": "Ambitious millennials and Gen-Z who've outgrown basic motivation content. They want frameworks, systems, and science — not just quotes. They read books like Atomic Habits and want deeper, actionable insights.",
    "content_tone": ["thought-provoking", "analytical", "empowering", "research-backed", "practical"],
    "tone_avoid": ["toxic hustle culture", "guru worship", "shame-based motivation", "pseudoscience"],
    "topic_categories": ["Habits", "Cognitive Biases", "Decision Making", "Productivity", "Emotional Intelligence", "Mindfulness", "Goal Setting", "Resilience"],
    "topic_keywords": ["habit stacking", "dopamine", "cognitive biases", "decision fatigue", "growth mindset", "neuroplasticity", "flow state", "journaling", "meditation", "stoicism"],
    "topic_avoid": ["manifestation pseudoscience", "law of attraction", "sigma male content", "hustle porn"],
    "content_philosophy": "Real self-improvement is boring — it's consistent small actions, not dramatic transformations. We respect our audience by giving them science over motivation porn. Every piece of content should leave someone with one concrete thing they can DO differently today.",
    "hook_themes": ["psychology tricks your brain plays", "habits of high performers (backed by data)", "why you self-sabotage", "cognitive biases controlling your life", "the science of motivation"],
    "reel_examples": [
        {"title": "THE 2-MINUTE RULE THAT CHANGED EVERYTHING", "content_lines": ["Struggling to build habits? Use the 2-minute rule.", "Want to read more? Read one page.", "Want to exercise? Put on your gym shoes.", "Want to meditate? Sit for 2 minutes.", "The secret: you're not building the habit", "You're building the IDENTITY of someone who does it", "Once the identity shifts, scaling is easy"]},
        {"title": "YOUR BRAIN IS LYING TO YOU — HERE'S HOW", "content_lines": ["Confirmation bias: you only see evidence that supports what you already believe", "Dunning-Kruger: the less you know, the more confident you feel", "Sunk cost fallacy: you keep going because you've already invested", "Availability heuristic: you overestimate risks you can easily recall", "Your brain isn't broken — it's taking shortcuts", "Awareness is the first step to better decisions"]},
        {"title": "DOPAMINE IS DESTROYING YOUR MOTIVATION", "content_lines": ["Every notification gives you a tiny dopamine hit", "Your brain adapts — it needs MORE stimulation", "Eventually, normal activities feel boring and pointless", "This is why reading feels impossible after scrolling", "The fix: dopamine fasting isn't pseudoscience", "Remove high-stimulation for 24 hours weekly", "Your baseline resets. Motivation returns."]},
        {"title": "OVERTHINKING IS NOT A PERSONALITY TRAIT", "content_lines": ["Overthinking isn't 'just who you are'", "It's a pattern your nervous system learned", "Usually from environments where mistakes were punished", "Your brain is trying to protect you from threat", "But the threat isn't real anymore", "Retraining: set a 10-minute decision timer", "After 10 minutes, commit and move forward"]},
        {"title": "WHY MOTIVATION ALWAYS FADES (AND WHAT REPLACES IT)", "content_lines": ["Motivation is an emotion — it comes and goes", "Discipline sounds good but burns out too", "The real answer: environment design", "Make the right thing the EASY thing", "Put your gym bag by the door", "Delete social media from your home screen", "You don't rise to your goals — you fall to your systems"]},
        {"title": "5 SIGNS YOU'RE ACTUALLY GROWING", "content_lines": ["1. Things that used to trigger you don't anymore", "2. You set boundaries without guilt", "3. You're comfortable with uncertainty", "4. You choose long-term over instant gratification", "5. You can be wrong without it destroying your identity", "Growth is quiet. It happens in the boring middle.", "Keep going."]},
        {"title": "THE PARADOX OF CHOICE EXPLAINED", "content_lines": ["More options should make us happier, right?", "A Columbia study: 24 jams displayed, 3% bought", "6 jams displayed, 30% bought — 10x more sales", "Too many choices cause decision paralysis", "This applies to your life: career, dating, goals", "Limit your options intentionally", "Constraint creates clarity"]},
        {"title": "HOW TO STOP COMPARING YOURSELF TO OTHERS", "content_lines": ["Comparison isn't a character flaw — it's biological", "Our ancestors needed it for survival hierarchy", "But social media hijacked this instinct", "You're comparing your behind-the-scenes to highlight reels", "The fix: compare yourself to yourself 1 year ago", "Track YOUR progress, not theirs", "The only scoreboard that matters is your own"]},
        {"title": "THE JOURNAL PROMPT THAT THERAPISTS RECOMMEND", "content_lines": ["Write down what's bothering you", "Then ask: 'Is this within my control?'", "If yes — write the next action step", "If no — write 'I'm choosing to let this go'", "This is the core of CBT (cognitive behavioral therapy)", "Externalize the thought. Examine it. Decide.", "5 minutes of journaling replaces hours of ruminating"]},
        {"title": "PROCRASTINATION ISN'T LAZINESS — IT'S THIS", "content_lines": ["Procrastination is an emotion regulation problem, not a time management problem", "You avoid tasks that trigger negative emotions:", "Fear of failure. Fear of judgment. Perfectionism.", "Your brain chooses short-term relief over long-term benefit", "The fix: identify the EMOTION behind the avoidance", "Then address the emotion, not the task", "Therapy > productivity hacks"]}
    ],
    "post_examples": [
        {"title": "THE SCIENCE OF HABIT FORMATION (IT'S NOT 21 DAYS)", "slides": ["The '21 days to form a habit' myth comes from a misquoted plastic surgeon in the 1960s. The actual science tells a very different story — and understanding it changes how you approach change.", "A 2009 study at University College London tracked 96 people forming new habits. The average time to automaticity was 66 days — but ranged from 18 to 254 days depending on the habit complexity.", "The 4-step habit loop (from neuroscience): Cue → Craving → Response → Reward. To build a habit, make the cue obvious, the craving attractive, the response easy, and the reward satisfying. To break one, invert each step.", "The practical protocol: Start impossibly small (2-minute version). Stack it onto an existing habit ('After I pour my coffee, I will journal for 2 minutes'). Track it visually (don't break the chain). Miss one day? Never miss two. Consistency > intensity."], "study_ref": "European Journal of Social Psychology, 2009 — Phillippa Lally et al."},
        {"title": "WHY SMART PEOPLE MAKE DUMB DECISIONS", "slides": ["Intelligence doesn't protect you from cognitive biases — in some cases, it makes you MORE susceptible. A study at Yale found that smarter people are better at rationalizing their biased decisions.", "The 5 cognitive biases that trap smart people most: Anchoring (first info disproportionately influences you), Confirmation bias (seeking evidence for what you already believe), Overconfidence effect, Narrative fallacy, and Survivorship bias.", "Real-world damage: Anchoring costs the average person $1,200/year in negotiations alone. Confirmation bias leads to investment losses averaging 3.4% annually. These aren't personality quirks — they're systematic errors in human cognition.", "The defense system: 1) Pre-commit to criteria before making decisions. 2) Actively seek disconfirming evidence. 3) Use checklists for important decisions. 4) Sleep on major decisions (reduces emotional bias by 40%). 5) Ask: 'What would I advise a friend?'"], "study_ref": "Yale Cognitive Science Lab, 2022 — Cognitive Sophistication and Bias"},
        {"title": "THE NEUROSCIENCE OF WILLPOWER (AND WHY IT RUNS OUT)", "slides": ["Willpower isn't unlimited — it operates like a muscle that fatigues with use. This is called 'ego depletion,' and understanding it explains why you eat junk food after a stressful day.", "A landmark study by Roy Baumeister showed that participants who resisted cookies performed worse on subsequent puzzles. Decision-making, emotional regulation, and self-control all draw from the same limited resource.", "Your willpower is highest in the morning and depletes throughout the day. This is why most diet failures happen at night, most impulsive purchases happen in the evening, and most arguments happen after work.", "The system-based approach: Don't rely on willpower — design your environment instead. Remove temptations physically. Make important decisions in the morning. Automate routine choices. Use implementation intentions ('If X happens, I will do Y'). Save willpower for what truly matters."], "study_ref": "Baumeister et al., Journal of Personality and Social Psychology, 2018"},
        {"title": "FLOW STATE: HOW TO ACCESS PEAK PERFORMANCE ON DEMAND", "slides": ["Flow state — being 'in the zone' — increases productivity by 500% according to McKinsey research. It's not random. Neuroscience has identified exactly how to trigger it.", "The 4 conditions for flow: 1) Clear goals (know exactly what you're doing), 2) Immediate feedback (know if you're doing it well), 3) Challenge-skill balance (4% harder than your current ability), 4) Deep focus without interruption (minimum 15-25 minutes).", "The neurochemistry: During flow, your brain releases dopamine, norepinephrine, endorphins, anandamide, and serotonin simultaneously. This cocktail enhances pattern recognition by 400% and creative thinking by 600%.", "The practical trigger sequence: 1) Eliminate ALL distractions (phone in another room). 2) Choose a task slightly above your skill level. 3) Set a clear, specific goal for the session. 4) Do 5 minutes of focused breathing to transition. 5) Work for 90-120 minutes uninterrupted. Schedule flow blocks daily."], "study_ref": "McKinsey & Company, 2021 — Flow Research + Csikszentmihalyi Framework"},
        {"title": "WHY GRATITUDE JOURNALS ACTUALLY WORK (THE BRAIN SCIENCE)", "slides": ["Gratitude journaling sounds like a cliché, but the neuroscience behind it is robust. A UC Davis study found that participants who wrote 5 gratitudes weekly for 10 weeks were 25% happier and exercised 33% more.", "The mechanism: Gratitude activates the hypothalamus (regulating stress) and the ventral tegmental area (producing dopamine). Writing specifically — not just thinking — creates stronger neural pathways.", "Consistent gratitude practice physically changes brain structure. An fMRI study showed that after 3 months of daily gratitude journaling, the medial prefrontal cortex showed increased gray matter — the region responsible for decision-making and emotional regulation.", "The optimal protocol: Write 3 specific things each morning (not vague — 'the warm coffee at 7am' beats 'I'm grateful for coffee'). Include WHY it matters. Do it at the same time daily. Studies show morning journaling has stronger effects on mood than evening."], "study_ref": "UC Davis, Emmons & McCullough, 2003 + Indiana University fMRI Study, 2021"},
        {"title": "THE 5 TYPES OF REST YOU'RE NOT GETTING", "slides": ["You're sleeping 8 hours but still exhausted. That's because sleep only addresses physical rest. Dr. Saundra Dalton-Smith's research identifies 7 types of rest — most people are deficient in at least 3.", "Physical rest (sleep + stretching), Mental rest (breaks every 90 min, brain dump journaling), Emotional rest (expressing feelings honestly, setting boundaries), Social rest (time alone if you're always 'on' around others).", "Sensory rest (reducing screen time, silence, nature), Creative rest (appreciating beauty, walking in nature, consuming art), Spiritual rest (purpose, community, meditation — the sense of belonging to something larger).", "The audit: Rate each type of rest 1-10 for your current life. Your lowest scores are your biggest energy leaks. Pick the lowest one and commit to ONE action this week: a walk in nature (sensory + creative), an honest conversation (emotional), or 30 minutes of solitude (social)."], "study_ref": "Dr. Saundra Dalton-Smith, Sacred Rest, 2019 + TED Talk Research"},
        {"title": "HOW TO ACTUALLY CHANGE YOUR IDENTITY", "slides": ["Behavior change fails when it conflicts with your identity. 'I'm trying to quit smoking' vs 'I'm not a smoker.' The second person doesn't need willpower — their identity does the work.", "James Clear's identity-based framework: Outcome-based goals ('I want to lose weight') have a 10% success rate. Identity-based goals ('I'm becoming someone who takes care of their body') succeed at 40%+.", "The evidence loop: Every action is a vote for the person you want to become. One workout = one vote for 'I'm an athlete.' One page read = one vote for 'I'm a reader.' No single vote is decisive, but the majority wins over time.", "The protocol: 1) Decide who you want to become (identity, not outcome). 2) Find the smallest action that proves it (1 pushup = athlete identity). 3) Do it consistently until it becomes automatic. 4) Then scale. You don't change your behavior — you change your self-image, and behavior follows."], "study_ref": "James Clear, Atomic Habits + Duckworth et al., Identity-Based Motivation, 2021"},
        {"title": "THE DECISION FATIGUE EPIDEMIC", "slides": ["The average adult makes 35,000 decisions per day. Each one depletes your cognitive resources. By afternoon, your decision quality drops 40% — a phenomenon called 'decision fatigue.'", "A famous study of Israeli judges found that prisoners reviewed in the morning received parole 65% of the time. After lunch break, it dropped to nearly 0%. The judges weren't cruel — they were cognitively exhausted and defaulted to 'no.'", "Decision fatigue explains: why you eat junk food at night, why online shopping peaks at 8pm, why arguments happen in the evening, why CEOs wear the same outfit daily, and why willpower 'runs out.'", "Combat decision fatigue: 1) Make important decisions before noon. 2) Automate recurring decisions (meal prep, capsule wardrobe). 3) Use the 'two-option rule' — limit choices to A or B. 4) Batch similar decisions together. 5) Create default responses for common situations."], "study_ref": "PNAS, 2011 — Danziger, Levav & Avnaim-Pesso, 'Extraneous factors in judicial decisions'"},
        {"title": "NEUROPLASTICITY: YOUR BRAIN CAN CHANGE AT ANY AGE", "slides": ["Until the 1990s, scientists believed adult brains were fixed. We now know the brain rewires itself throughout life — a property called neuroplasticity. You can literally change how you think.", "London taxi drivers have measurably larger hippocampi (spatial memory region) than bus drivers. Musicians have larger auditory cortices. Meditation practitioners show increased gray matter in the prefrontal cortex after just 8 weeks.", "The two types of neuroplasticity: Structural (new neural connections physically form) and Functional (existing pathways strengthen or weaken based on use). 'Neurons that fire together, wire together' — what you practice grows.", "How to leverage neuroplasticity: 1) Learn something genuinely difficult (not passive consumption). 2) Practice it consistently for 6+ weeks. 3) Sleep well — consolidation happens during sleep. 4) Exercise — BDNF (brain-derived neurotrophic factor) from exercise is literally 'miracle-gro for the brain.' Your brain at 50 can be sharper than at 25."], "study_ref": "Nature Neuroscience, 2020 — Neuroplasticity Across the Lifespan"},
        {"title": "THE PARETO PRINCIPLE FOR YOUR ENTIRE LIFE", "slides": ["80% of your results come from 20% of your efforts. Vilfredo Pareto discovered this in 1896 studying land ownership — and it applies to nearly everything in modern life.", "In business: 80% of revenue comes from 20% of customers. In fitness: 80% of your gains come from 20% of exercises (compound movements). In relationships: 80% of your happiness comes from 20% of your relationships. In productivity: 80% of meaningful output comes from 20% of your work hours.", "The power move: Identify YOUR vital 20%. Track your time for one week. Which activities produce the most results? Which relationships give you the most energy? Which work tasks actually move the needle?", "Then restructure ruthlessly: Double down on your 20% and eliminate, delegate, or minimize the rest. This isn't about working harder — it's about working on the RIGHT things. Most people optimize the 80% that barely matters while neglecting the 20% that drives everything."], "study_ref": "Koch, R. 'The 80/20 Principle' + Harvard Business Review Productivity Studies, 2023"}
    ],
    "image_style_description": "Thoughtful, minimal aesthetics with deep purple/indigo tones and warm amber accents. Clean typography, brain illustrations, conceptual diagrams.",
    "image_palette_keywords": ["purple", "indigo", "amber", "minimal", "thoughtful", "conceptual"],
    "brand_personality": "A wise friend who reads psychology research for fun and makes complex behavioral science feel like a conversation over tea. Thoughtful, not preachy.",
    "brand_focus_areas": ["habit formation", "cognitive psychology", "decision-making", "emotional intelligence", "mindset shifts"],
    "parent_brand_name": "",
    "cta_options": [
        {"text": "Follow for daily mindset shifts backed by science", "weight": 30},
        {"text": "Save this for when you need a reset", "weight": 25},
        {"text": "Share with someone who needs to hear this today", "weight": 20},
        {"text": "Follow for more psychology-based growth tips", "weight": 25}
    ],
    "hashtags": ["#selfimprovement", "#mindset", "#personaldevelopment", "#habits", "#psychology", "#growthmindset", "#motivation"],
    "competitor_accounts": [],
    "discovery_hashtags": ["#cognitivebias", "#habitscience", "#emotionalintelligence", "#behavioralscience", "#mentalmodels"],
    "citation_style": "academic",
    "citation_source_types": ["cognitive psychology journals", "behavioral science research", "neuroscience studies"],
    "carousel_cta_topic": "personal development",
    "carousel_cta_options": [
        {"text": "Save this framework for later", "weight": 40},
        {"text": "Share with someone on their growth journey", "weight": 30},
        {"text": "Follow for weekly deep dives into the mind", "weight": 30}
    ],
    "follow_section_text": "Follow @{account} for science-backed personal development",
    "save_section_text": "Save this — read it again when you need perspective",
    "disclaimer_text": "This content is for educational purposes. For mental health concerns, please consult a licensed professional.",
    "yt_title_examples": [
        "The Overthinking Cure That Neuroscientists Actually Recommend",
        "Why Discipline Is a Myth (And What to Build Instead)",
        "I Tried Every Morning Routine for 30 Days — Only ONE Worked",
        "The Cognitive Bias That's Secretly Ruining Your Decisions",
        "Why Smart People Stay Stuck (The Dunning-Kruger Trap Explained)",
        "How I Broke My Phone Addiction Using Dopamine Science",
        "The 2-Minute Journaling Method Backed by 200+ Studies"
    ],
    "yt_title_bad_examples": [
        "Self-Improvement Tips",
        "How to Be More Productive",
        "My Morning Routine",
        "Mindset Advice",
        "How to Stop Overthinking"
    ]
}
