import { useState } from 'react'
import { useParams, useNavigate } from 'react-router-dom'
import { 
  ArrowLeft,
  RefreshCw,
  Trash2,
  Download,
  Calendar,
  Edit2,
  Copy,
  Play,
  Loader2,
  AlertCircle,
  Check,
  Clock,
  CalendarClock,
  Youtube,
  Pencil,
  Save,
  X,
  Music,
  Shuffle,
  ChevronDown,
  ChevronUp,
} from 'lucide-react'
import toast from 'react-hot-toast'
import { format } from 'date-fns'
import { 
  useJob, 
  useDeleteJob, 
  useRegenerateJob, 
  useRegenerateBrand,
  useUpdateJob,
  useJobNextSlots,
  useUpdateBrandStatus,
  useUpdateBrandContent,
  useRetryJob,
  useChangeJobMusic,
} from '@/features/jobs'
import { useAutoScheduleReel } from '@/features/scheduling'
import { useTrendingMusic } from '@/features/brands/api/use-trending-music'
import { BrandBadge, getBrandLabel, getBrandColor } from '@/features/brands'
import { StatusBadge, JobDetailSkeleton, Modal } from '@/shared/components'
import { createFacebookCaption } from '@/shared/lib/captionUtils'
import { PostJobDetail } from './PostJobDetail'
import type { BrandName, BrandOutput } from '@/shared/types'

export function JobDetailPage() {
  const { jobId } = useParams<{ jobId: string }>()
  const navigate = useNavigate()
  const id = jobId || ''
  
  const { data: job, isLoading, error } = useJob(id)
  const { data: nextSlots } = useJobNextSlots(id)
  const deleteJob = useDeleteJob()
  const regenerateJob = useRegenerateJob()
  const regenerateBrand = useRegenerateBrand()
  const updateJob = useUpdateJob()
  const updateBrandStatus = useUpdateBrandStatus()
  const updateBrandContent = useUpdateBrandContent()
  const autoSchedule = useAutoScheduleReel()
  const retryJob = useRetryJob()
  const changeMusic = useChangeJobMusic()
  const { data: trendingMusicData } = useTrendingMusic()
  const trendingTracks = trendingMusicData?.tracks ?? []
  
  // Modal states
  const [deleteModalOpen, setDeleteModalOpen] = useState(false)
  const [editTitleModalOpen, setEditTitleModalOpen] = useState(false)
  const [editedTitle, setEditedTitle] = useState('')
  const [customScheduleModalOpen, setCustomScheduleModalOpen] = useState(false)
  const [customScheduleDate, setCustomScheduleDate] = useState('')
  const [customScheduleTime, setCustomScheduleTime] = useState('')
  
  // Loading states
  const [schedulingBrand, setSchedulingBrand] = useState<BrandName | null>(null)
  const [schedulingAll, setSchedulingAll] = useState(false)
  const [schedulingCustom, setSchedulingCustom] = useState(false)

  // Per-brand title editing state
  const [editingTitleBrand, setEditingTitleBrand] = useState<string | null>(null)
  const [editingTitleValue, setEditingTitleValue] = useState('')
  const [savingTitle, setSavingTitle] = useState(false)

  // Per-brand schedule modal state
  const [brandScheduleModalBrand, setBrandScheduleModalBrand] = useState<BrandName | null>(null)
  const [brandScheduleMode, setBrandScheduleMode] = useState<'auto' | 'custom'>('auto')
  const [brandCustomDate, setBrandCustomDate] = useState('')
  const [brandCustomTime, setBrandCustomTime] = useState('')
  const [showPromptDetails, setShowPromptDetails] = useState(false)
  
  const isGenerating = job?.status === 'generating' || job?.status === 'pending'
  const isTextVideo = job?.variant === 'text_video'

  // Clean title for display: collapse ALL-CAPS multiline titles to single-line Title Case
  const formatDisplayTitle = (raw: string) => {
    const singleLine = raw.replace(/\n/g, ' ').replace(/\s+/g, ' ').trim()
    // If all uppercase, convert to title case
    if (singleLine === singleLine.toUpperCase() && singleLine.length > 1) {
      return singleLine.replace(/\w\S*/g, w => w.charAt(0).toUpperCase() + w.slice(1).toLowerCase())
    }
    return singleLine
  }

  // Detect auto-generated jobs: fixed_title is false/undefined AND multiple brands
  // This works even while brands are still generating (before per-brand titles appear)
  const isAutoGenerated = job ? !job.fixed_title && (job.brands?.length || 0) > 1 : false

  // Per-brand title helpers
  const startEditingTitle = (brand: string) => {
    const output = job?.brand_outputs?.[brand as BrandName]
    setEditingTitleValue(output?.title || job?.title || '')
    setEditingTitleBrand(brand)
  }

  const saveBrandTitle = async () => {
    if (!editingTitleBrand || !job) return
    setSavingTitle(true)
    try {
      await updateBrandContent.mutateAsync({
        id: job.id,
        brand: editingTitleBrand as BrandName,
        data: { title: editingTitleValue },
      })
      toast.success('Title updated!')
      setEditingTitleBrand(null)
    } catch {
      toast.error('Failed to update title')
    } finally {
      setSavingTitle(false)
    }
  }
  
  const allScheduled = job ? Object.entries(job.brand_outputs || {})
    .filter(([_, output]) => output.status === 'completed' || output.status === 'scheduled')
    .every(([_, output]) => output.status === 'scheduled') : false
  
  // Dismiss a brand — mark it so it's excluded from Schedule All
  const handleDismissBrand = async (brand: BrandName) => {
    if (!job) return
    try {
      await updateBrandStatus.mutateAsync({ id, brand, status: 'dismissed' })
      toast.success(`${getBrandLabel(brand)} removed from scheduling`)
    } catch {
      toast.error('Failed to dismiss brand')
    }
  }

  // Restore a dismissed brand back to completed
  const handleRestoreBrand = async (brand: BrandName) => {
    if (!job) return
    try {
      await updateBrandStatus.mutateAsync({ id, brand, status: 'completed' })
      toast.success(`${getBrandLabel(brand)} restored`)
    } catch {
      toast.error('Failed to restore brand')
    }
  }
  
  const handleDelete = async () => {
    try {
      await deleteJob.mutateAsync(id)
      toast.success('Job deleted')
      navigate('/history')
    } catch {
      toast.error('Failed to delete job')
    }
  }
  
  const handleRegenerateBrand = async (brand: BrandName) => {
    try {
      await regenerateBrand.mutateAsync({ id, brand })
      toast.success(`Regenerating ${getBrandLabel(brand)}`)
    } catch {
      toast.error('Failed to regenerate')
    }
  }
  
  const openEditTitleModal = () => {
    setEditedTitle(job?.title || '')
    setEditTitleModalOpen(true)
  }
  
  const handleSaveTitle = async () => {
    if (!editedTitle.trim()) {
      toast.error('Title cannot be empty')
      return
    }
    
    try {
      await updateJob.mutateAsync({ id, data: { title: editedTitle } })
      setEditTitleModalOpen(false)
      toast.success('Title updated')
      await regenerateJob.mutateAsync(id)
      toast.success('Regenerating with new title')
    } catch {
      toast.error('Failed to update title')
    }
  }
  
  const openBrandScheduleModal = (brand: BrandName) => {
    setBrandScheduleModalBrand(brand)
    setBrandScheduleMode('auto')
    const tomorrow = new Date()
    tomorrow.setDate(tomorrow.getDate() + 1)
    setBrandCustomDate(tomorrow.toISOString().split('T')[0])
    setBrandCustomTime('12:00')
  }

  const confirmBrandSchedule = () => {
    if (!brandScheduleModalBrand || !job) return
    const output = job.brand_outputs?.[brandScheduleModalBrand]
    if (!output) return

    let customTime: string | undefined
    if (brandScheduleMode === 'custom' && brandCustomDate && brandCustomTime) {
      const dt = new Date(`${brandCustomDate}T${brandCustomTime}:00`)
      if (dt <= new Date()) {
        toast.error('Please select a future date and time')
        return
      }
      customTime = dt.toISOString()
    }

    const brand = brandScheduleModalBrand
    setBrandScheduleModalBrand(null)
    handleScheduleBrand(brand, output, customTime)
  }

  const handleScheduleBrand = async (brand: BrandName, output: BrandOutput, customScheduleTime?: string) => {
    if (!output.reel_id || !job) {
      toast.error('No reel to schedule')
      return
    }
    
    const caption = output.caption || `${job.title}\n\nGenerated content for ${brand}`
    
    setSchedulingBrand(brand)
    try {
      await autoSchedule.mutateAsync({
        brand,
        reel_id: output.reel_id,
        variant: job.variant,
        caption: caption,
        yt_title: output.yt_title,
        yt_thumbnail_path: output.yt_thumbnail_path,
        video_path: output.video_path,
        thumbnail_path: output.thumbnail_path,
        platforms: job.platforms,
        ...(customScheduleTime ? { scheduled_time: customScheduleTime } : {}),
      })
      
      await updateBrandStatus.mutateAsync({
        id,
        brand,
        status: 'scheduled',
      })
      
      toast.success(`${getBrandLabel(brand)} scheduled!`)
    } catch {
      toast.error('Failed to schedule')
    } finally {
      setSchedulingBrand(null)
    }
  }
  
  const handleScheduleAll = async () => {
    if (!job) return
    
    const completedBrands = Object.entries(job.brand_outputs || {})
      .filter(([_, output]) => output.status === 'completed')
      .map(([brand]) => brand as BrandName)
    
    if (completedBrands.length === 0) {
      toast.error('No completed brands to schedule')
      return
    }
    
    setSchedulingAll(true)
    let scheduled = 0
    let failed = 0
    
    for (const brand of completedBrands) {
      const output = job.brand_outputs[brand]
      if (output?.reel_id) {
        try {
          const caption = output.caption || `${job.title}\n\nGenerated content for ${brand}`
          
          await autoSchedule.mutateAsync({
            brand,
            reel_id: output.reel_id,
            variant: job.variant,
            caption: caption,
            yt_title: output.yt_title,  // Pass YouTube title for YT Shorts
            yt_thumbnail_path: output.yt_thumbnail_path,  // Clean AI image for YouTube
            video_path: output.video_path,
            thumbnail_path: output.thumbnail_path,
            platforms: job.platforms,  // Pass platforms from job
          })
          await updateBrandStatus.mutateAsync({
            id,
            brand,
            status: 'scheduled',
          })
          scheduled++
        } catch (error) {
          console.error(`Failed to schedule ${brand}:`, error)
          failed++
        }
      }
    }
    
    setSchedulingAll(false)
    
    if (scheduled > 0) {
      const message = failed > 0 
        ? `✅ ${scheduled} brand${scheduled !== 1 ? 's' : ''} scheduled! ${failed} failed.`
        : scheduled === 1
          ? '🎉 Reel scheduled successfully!'
          : `🎉 All ${scheduled} brands scheduled successfully!`
      
      toast.success(message, { duration: 4000 })
      
      setTimeout(() => {
        navigate('/calendar')
      }, 1500)
    } else if (failed > 0) {
      toast.error('Failed to schedule brands')
    }
  }
  
  const openCustomScheduleModal = () => {
    // Set default to tomorrow at 10:00
    const tomorrow = new Date()
    tomorrow.setDate(tomorrow.getDate() + 1)
    setCustomScheduleDate(tomorrow.toISOString().split('T')[0])
    setCustomScheduleTime('10:00')
    setCustomScheduleModalOpen(true)
  }
  
  const isCustomScheduleInPast = (() => {
    if (!customScheduleDate || !customScheduleTime) return false
    const selected = new Date(`${customScheduleDate}T${customScheduleTime}`)
    return selected <= new Date()
  })()

  const handleCustomScheduleAll = async () => {
    if (!job || !customScheduleDate || !customScheduleTime) {
      toast.error('Please select a date and time')
      return
    }
    
    if (isCustomScheduleInPast) {
      toast.error('Cannot schedule in the past')
      return
    }
    
    const completedBrands = Object.entries(job.brand_outputs || {})
      .filter(([_, output]) => output.status === 'completed')
      .map(([brand]) => brand as BrandName)
    
    if (completedBrands.length === 0) {
      toast.error('No completed brands to schedule')
      return
    }
    
    setSchedulingCustom(true)
    let scheduled = 0
    let failed = 0
    
    // Parse base datetime
    const baseDateTime = new Date(`${customScheduleDate}T${customScheduleTime}`)
    
    for (let i = 0; i < completedBrands.length; i++) {
      const brand = completedBrands[i]
      const output = job.brand_outputs[brand]
      if (output?.reel_id) {
        try {
          const caption = output.caption || `${job.title}\n\nGenerated content for ${brand}`
          
          // Stagger brands by 1 hour each
          const scheduledTime = new Date(baseDateTime)
          scheduledTime.setHours(scheduledTime.getHours() + i)
          
          await autoSchedule.mutateAsync({
            brand,
            reel_id: output.reel_id,
            variant: job.variant,
            caption: caption,
            yt_title: output.yt_title,  // Pass YouTube title for YT Shorts
            yt_thumbnail_path: output.yt_thumbnail_path,  // Clean AI image for YouTube
            video_path: output.video_path,
            thumbnail_path: output.thumbnail_path,
            scheduled_time: scheduledTime.toISOString(),
            platforms: job.platforms,  // Pass platforms from job
          })
          await updateBrandStatus.mutateAsync({
            id,
            brand,
            status: 'scheduled',
          })
          scheduled++
        } catch (error) {
          console.error(`Failed to schedule ${brand}:`, error)
          failed++
        }
      }
    }
    
    setSchedulingCustom(false)
    setCustomScheduleModalOpen(false)
    
    if (scheduled > 0) {
      const message = failed > 0 
        ? `✅ ${scheduled} brand${scheduled !== 1 ? 's' : ''} scheduled for ${customScheduleDate}! ${failed} failed.`
        : scheduled === 1
          ? `🎉 Reel scheduled for ${customScheduleDate}!`
          : `🎉 All ${scheduled} brands scheduled for ${customScheduleDate}!`
      
      toast.success(message, { duration: 4000 })
      
      setTimeout(() => {
        navigate('/calendar')
      }, 1500)
    } else if (failed > 0) {
      toast.error('Failed to schedule brands')
    }
  }
  
  const handleDownload = (_brand: BrandName, output: BrandOutput) => {
    if (output.video_path) {
      const link = document.createElement('a')
      link.href = output.video_path
      link.download = `${_brand}_${output.reel_id || 'reel'}.mp4`
      link.click()
    }
  }
  
  const copyToClipboard = (text: string, label: string) => {
    navigator.clipboard.writeText(text)
    toast.success(`${label} copied!`)
  }
  
  if (isLoading) return <JobDetailSkeleton />
  
  if (error || !job) {
    return (
      <div className="text-center py-12">
        <AlertCircle className="w-12 h-12 text-red-500 mx-auto mb-4" />
        <h2 className="text-xl font-semibold text-gray-900 mb-2">Job not found</h2>
        <button onClick={() => navigate('/history')} className="inline-flex items-center gap-2 px-4 py-2 text-sm font-semibold text-white bg-teal-600 rounded-lg hover:brightness-110 transition mt-4">
          Back to Jobs
        </button>
      </div>
    )
  }

  // Delegate to post-specific detail view
  if (job.variant === 'post') {
    return <PostJobDetail job={job} />
  }
  
  const completedCount = Object.values(job.brand_outputs || {})
    .filter(o => o.status === 'completed').length
  const dismissedCount = Object.values(job.brand_outputs || {})
    .filter(o => o.status === 'dismissed').length
  const scheduledCount = Object.values(job.brand_outputs || {})
    .filter(o => o.status === 'scheduled').length
  const scheduleButtonLabel = completedCount === 1 ? 'Schedule Reel' : scheduledCount > 0 ? `Schedule ${completedCount} Remaining` : `Schedule All (${completedCount})`
  
  return (
    <div className="space-y-3 max-w-[1060px] mx-auto">
      {/* Top bar */}
      <div className="flex items-center justify-between mb-1">
        <button
          onClick={() => navigate('/history')}
          className="inline-flex items-center gap-1.5 text-sm font-medium text-gray-500 hover:text-gray-900 transition-colors py-1.5"
        >
          <ArrowLeft className="w-[18px] h-[18px]" />
          Back
        </button>
        <div className="flex items-center gap-1.5">
          {!isAutoGenerated && (
            <button
              onClick={openEditTitleModal}
              disabled={isGenerating || allScheduled}
              className="inline-flex items-center gap-1.5 px-3 py-[7px] text-[13px] font-medium text-gray-500 bg-white border border-gray-200 rounded-[7px] hover:bg-gray-50 hover:text-gray-700 transition-colors"
              title={allScheduled ? "Cannot edit - brands are scheduled" : ""}
            >
              <Edit2 className="w-3.5 h-3.5" />
              Edit Title
            </button>
          )}
          <button
            onClick={() => setDeleteModalOpen(true)}
            disabled={isGenerating}
            className="inline-flex items-center gap-1.5 px-3 py-[7px] text-[13px] font-medium text-rose-600 bg-white border border-rose-200 rounded-[7px] hover:bg-rose-50 transition-colors"
          >
            <Trash2 className="w-3.5 h-3.5" />
            Delete
          </button>
        </div>
      </div>

      {/* Hero card */}
      <div className="bg-white rounded-[10px] border border-gray-200 shadow-sm p-6">
        <div className="flex items-center gap-2 mb-3 flex-wrap">
          <span className="text-xs font-mono text-gray-400 bg-gray-100 px-2.5 py-1 rounded-full">#{job.id}</span>
          <StatusBadge status={job.status} size="md" />
          {isTextVideo && (
            <span className="text-xs font-medium bg-violet-50 text-violet-600 px-2.5 py-1 rounded-full">FORMAT B</span>
          )}
        </div>
        {isAutoGenerated ? (
          <>
            <h1 className="text-xl font-bold text-gray-900 tracking-tight leading-snug">
              🤖 Auto-Generated Viral Reels
            </h1>
            <p className="text-gray-400 text-sm mt-1">
              {job.brands.length} brand{job.brands.length !== 1 ? 's' : ''} · each with unique title & content
              {dismissedCount > 0 && <span className="text-gray-500"> · {dismissedCount} dismissed</span>}
            </p>
            <span className="text-gray-400 text-xs">
              {format(new Date(job.created_at), 'MMMM d, yyyy · h:mm a')}
            </span>
          </>
        ) : (
          <>
            <h1 className="text-xl font-bold text-gray-900 tracking-tight leading-snug">
              {formatDisplayTitle(job.title)}
            </h1>
            <span className="text-gray-400 text-sm">
              {format(new Date(job.created_at), 'MMMM d, yyyy · h:mm a')}
            </span>
            
            {job.content_lines && job.content_lines.length > 0 && (
              <div className="mt-4 bg-gray-50 rounded-[7px] p-4">
                <p className="text-[11px] font-mono uppercase tracking-widest text-gray-400 mb-1.5">Source Content</p>
                {isTextVideo ? (
                  <p className="text-sm text-gray-500 leading-relaxed whitespace-pre-line">{job.content_lines.join('\n')}</p>
                ) : (
                  <ul className="list-disc list-inside space-y-0.5 text-sm text-gray-500 leading-relaxed">
                    {job.content_lines.map((line, idx) => (
                      <li key={idx}>{line}</li>
                    ))}
                  </ul>
                )}
              </div>
            )}
            
            {job.variant === 'dark' && job.ai_prompt && (
              <div className="mt-2 text-sm bg-violet-50 rounded-[7px] p-3 border border-violet-100">
                <p className="font-medium text-violet-700 mb-1">AI Background Prompt:</p>
                <p className="text-violet-600 italic">{job.ai_prompt}</p>
              </div>
            )}
          </>
        )}
        
        {job.error_message && (
          <div className="mt-3 text-sm bg-red-50 border border-red-200 rounded-[7px] p-3">
            <div className="flex items-start gap-2">
              <AlertCircle className="w-4 h-4 text-red-500 mt-0.5 flex-shrink-0" />
              <div className="flex-1">
                <p className="font-medium text-red-700">Error:</p>
                <p className="text-red-600">{job.error_message}</p>
              </div>
              {job.status === 'failed' && (
                <button
                  onClick={() => {
                    retryJob.mutate(id, {
                      onSuccess: () => toast.success('Retrying incomplete brands...'),
                      onError: (err: any) => toast.error(err?.message || 'Failed to retry job'),
                    })
                  }}
                  disabled={retryJob.isPending}
                  className="px-3 py-1.5 text-xs font-medium text-white bg-teal-600 rounded-[5px] hover:brightness-110 transition flex-shrink-0 flex items-center gap-1.5"
                >
                  {retryJob.isPending ? (
                    <Loader2 className="w-3 h-3 animate-spin" />
                  ) : (
                    <RefreshCw className="w-3 h-3" />
                  )}
                  Retry Incomplete
                </button>
              )}
            </div>
          </div>
        )}
      </div>
      
      {/* Quick Schedule Section */}
      {completedCount > 0 && (
        <div className="rounded-xl p-4 bg-gradient-to-r from-purple-900/40 to-blue-900/40 border border-purple-500/20 backdrop-blur-sm">
          <div className="flex items-center justify-between">
            <div className="flex items-center gap-3">
              <Calendar className="w-5 h-5 text-purple-400" />
              <div>
                <span className="font-semibold text-white">Quick Schedule</span>
                <span className="text-gray-400 ml-2">
                  {completedCount} brand{completedCount !== 1 ? 's' : ''} ready
                </span>
              </div>
            </div>
            <div className="flex items-center gap-2">
              <button
                onClick={handleScheduleAll}
                disabled={schedulingAll || schedulingCustom || isGenerating || allScheduled}
                className="flex items-center gap-2 px-4 py-2 text-sm font-medium text-white bg-purple-600 rounded-lg hover:bg-purple-700 transition-colors disabled:opacity-50"
                title={allScheduled ? "All brands already scheduled" : "Schedule to next available slots"}
              >
                {schedulingAll ? (
                  <Loader2 className="w-4 h-4 animate-spin" />
                ) : allScheduled ? (
                  <Check className="w-4 h-4" />
                ) : (
                  <Calendar className="w-4 h-4" />
                )}
                {allScheduled ? 'All Scheduled' : scheduleButtonLabel}
              </button>
              
              {!allScheduled && (
                <button
                  onClick={openCustomScheduleModal}
                  disabled={schedulingAll || schedulingCustom || isGenerating}
                  className="inline-flex items-center gap-1.5 px-3.5 py-2 text-[13px] font-medium text-gray-500 bg-white border border-gray-200 rounded-[7px] hover:bg-gray-50 hover:text-gray-700 transition-colors disabled:opacity-50"
                  title="Pick a custom date and time"
                >
                  <CalendarClock className="w-4 h-4" />
                  Custom
                </button>
              )}
            </div>
          </div>
        </div>
      )}
      
      {/* Music bar */}
      {!isGenerating && (
        <div className="bg-white rounded-[10px] border border-gray-200 shadow-sm border-l-[3px] border-l-gray-300 flex items-center justify-between p-3 px-4 flex-wrap gap-2.5">
          <div className="flex items-center gap-2">
            <Music className="w-[17px] h-[17px] text-teal-600" />
            <span className="font-semibold text-sm text-gray-900">Background Music</span>
            <span className="text-sm text-gray-400">
              · {job.music_source === 'trending_random' ? 'Random Trending' :
                 job.music_source === 'trending_pick' ? 'Trending Track' :
                 'No Music'}
            </span>
          </div>
          <div className="flex items-center gap-1.5">
              <select
                value={job.music_source ?? 'none'}
                onChange={(e) => {
                  const source = e.target.value
                  changeMusic.mutate(
                    { id, musicTrackId: null, musicSource: source },
                    {
                      onSuccess: () => toast.success(source === 'none' ? 'Music removed — regenerating videos…' : 'Music changed — regenerating videos…'),
                      onError: () => toast.error('Failed to change music'),
                    },
                  )
                }}
                disabled={changeMusic.isPending || allScheduled}
                className="px-3 py-1.5 text-sm border border-gray-200 rounded-[5px] bg-white text-gray-500 appearance-none pr-7 cursor-pointer bg-[url('data:image/svg+xml,%3Csvg%20xmlns=%27http://www.w3.org/2000/svg%27%20width=%2712%27%20height=%2712%27%20fill=%27%239ca3af%27%3E%3Cpath%20d=%27M2%204l4%204%204-4%27/%3E%3C/svg%3E')] bg-no-repeat bg-[right_8px_center]"
              >
                <option value="none">🔇 No Music</option>
                <option value="trending_random">🎲 Random Trending</option>
                {trendingTracks.length > 0 && <option value="trending_pick">🎵 Pick from Trending</option>}
              </select>
              {(job.music_source === 'trending_random') && (
                <button
                  onClick={() =>
                    changeMusic.mutate(
                      { id, musicTrackId: null, musicSource: 'trending_random' },
                      {
                        onSuccess: () => toast.success('New random trending music — regenerating videos…'),
                        onError: () => toast.error('Failed to re-roll music'),
                      },
                    )
                  }
                  disabled={changeMusic.isPending || allScheduled}
                  className="inline-flex items-center gap-1 px-2.5 py-1.5 text-xs font-medium text-gray-400 bg-white border border-gray-200 rounded-[5px] hover:text-gray-600 hover:border-gray-300 transition-colors disabled:opacity-50"
                  title="Re-roll random trending music"
                >
                  {changeMusic.isPending ? <Loader2 className="w-3.5 h-3.5 animate-spin" /> : <Shuffle className="w-3.5 h-3.5" />}
                  Re-roll
                </button>
              )}
            </div>
        </div>
      )}

      {/* Brand Sections */}
      <div className="grid gap-6">
        {job.brands?.map(brand => {
          const output = job.brand_outputs?.[brand] || { status: 'pending' }
          const isCompleted = output.status === 'completed'
          const isScheduled = output.status === 'scheduled'
          const isFailed = output.status === 'failed'
          const isDismissed = output.status === 'dismissed'
          const isBrandGenerating = output.status === 'generating' || output.status === 'pending'
          const slot = nextSlots?.[brand]
          
          return (
            <div
              key={brand}
              className={`rounded-[10px] overflow-hidden bg-white border border-gray-200 shadow-sm ${isDismissed ? 'opacity-50' : ''}`}
              style={{ borderTopColor: getBrandColor(brand), borderTopWidth: '3px' }}
            >
              {/* Brand Header */}
              <div className="p-4 border-b border-gray-100 flex items-center justify-between">
                <div className="flex items-center gap-3">
                  <BrandBadge brand={brand} size="md" />
                  <StatusBadge status={isDismissed ? 'dismissed' : output.status} />
                </div>
                
                <div className="flex items-center gap-2">
                  {slot && !isScheduled && !isDismissed && (
                    <div className="flex items-center gap-2 text-sm text-gray-400">
                      <Clock className="w-4 h-4" />
                      <span>Next slot: {slot.formatted}</span>
                    </div>
                  )}
                  {/* Dismiss / Restore button */}
                  {isDismissed ? (
                    <button
                      onClick={() => handleRestoreBrand(brand)}
                      className="flex items-center gap-1.5 px-2.5 py-1.5 text-xs font-medium text-teal-600 bg-teal-50 border border-teal-200 rounded-[5px] hover:bg-teal-100 transition-colors"
                      title="Restore this brand"
                    >
                      <RefreshCw className="w-3 h-3" />
                      Restore
                    </button>
                  ) : (isCompleted && !isGenerating) ? (
                    <button
                      onClick={() => handleDismissBrand(brand)}
                      className="flex items-center gap-1.5 px-2.5 py-1.5 text-xs font-medium text-rose-500 opacity-50 hover:opacity-100 transition-opacity rounded-[5px]"
                      title="Remove this brand from scheduling"
                    >
                      <X className="w-3 h-3" />
                      Dismiss
                    </button>
                  ) : null}
                </div>
              </div>
              
              {/* Content */}
              <div className="p-4">
                {isDismissed ? (
                  <div className="text-center py-6 text-gray-400">
                    <X className="w-8 h-8 mx-auto mb-2 text-gray-300" />
                    <p className="text-sm">Brand dismissed — won't be included in Schedule All</p>
                  </div>
                ) : isBrandGenerating ? (
                  <div className="flex flex-col items-center justify-center py-12">
                    <Loader2 className="w-10 h-10 text-teal-600 animate-spin mb-4" />
                    <p className="text-gray-600 font-medium mb-2">
                      {output.progress_message || `Generating ${getBrandLabel(brand)}...`}
                    </p>
                    {typeof output.progress_percent === 'number' && (
                      <div className="w-full max-w-xs">
                        <div className="flex justify-between text-xs text-gray-400 mb-1">
                          <span>Progress</span>
                          <span>{output.progress_percent}%</span>
                        </div>
                        <div className="h-2 bg-gray-100 rounded-full overflow-hidden">
                          <div 
                            className="h-full bg-teal-500 transition-all duration-500 ease-out"
                            style={{ width: `${output.progress_percent}%` }}
                          />
                        </div>
                      </div>
                    )}
                  </div>
                ) : isFailed ? (
                  <div className="text-center py-8">
                    <AlertCircle className="w-10 h-10 text-red-500 mx-auto mb-4" />
                    <p className="text-gray-500 mb-4">{output.error || 'Generation failed'}</p>
                    <button
                      onClick={() => handleRegenerateBrand(brand)}
                      disabled={regenerateBrand.isPending}
                      className="inline-flex items-center gap-2 px-4 py-2 text-sm font-medium text-white bg-teal-600 rounded-[7px] hover:brightness-110 transition disabled:opacity-50"
                    >
                      <RefreshCw className="w-4 h-4" />
                      Retry
                    </button>
                  </div>
                ) : (isCompleted || isScheduled) ? (
                  <div className="space-y-4">
                    {/* Per-brand AI prompt (auto-generated jobs) */}
                    {isAutoGenerated && output.ai_prompt && (
                      <div className="text-sm bg-violet-50 rounded-[7px] p-3 border border-violet-100">
                        <p className="font-medium text-violet-600 mb-1 text-xs">AI Prompt:</p>
                        <p className="text-violet-500 italic text-xs">{output.ai_prompt}</p>
                      </div>
                    )}
                    
                    {/* Main content area - Media + Content Lines side by side */}
                    <div className="grid grid-cols-1 lg:grid-cols-2 gap-4">
                      {/* Left side: Media Preview - 3 columns: IG/FB Thumbnail, YT Thumbnail, Video */}
                      <div className="grid grid-cols-3 gap-3">
                        {/* IG/FB Thumbnail */}
                        <div>
                          <p className="text-xs text-gray-400 mb-1 text-center font-mono">IG/FB</p>
                          {output.thumbnail_path ? (
                            <div className="aspect-[9/16] bg-gray-50 rounded-[7px] overflow-hidden border border-gray-100">
                              <img
                                src={output.thumbnail_path}
                                alt={`${brand} thumbnail`}
                                className="w-full h-full object-cover object-top"
                              />
                            </div>
                          ) : (
                            <div className="aspect-[9/16] bg-gray-50 rounded-[7px] flex flex-col items-center justify-center text-gray-300 p-2 border border-gray-100">
                              <AlertCircle className="w-8 h-8 mb-1" />
                              <p className="text-xs text-center">No thumbnail</p>
                            </div>
                          )}
                        </div>
                        
                        {/* YouTube Thumbnail */}
                        <div>
                          <p className="text-xs text-gray-400 mb-1 text-center font-mono">YouTube</p>
                          {output.yt_thumbnail_path ? (
                            <div className="aspect-[9/16] bg-gray-50 rounded-[7px] overflow-hidden border border-gray-100">
                              <img
                                src={output.yt_thumbnail_path}
                                alt={`${brand} YouTube thumbnail`}
                                className="w-full h-full object-cover object-top"
                              />
                            </div>
                          ) : (
                            <div className="aspect-[9/16] bg-gray-50 rounded-[7px] flex flex-col items-center justify-center text-gray-300 p-2 border border-gray-100">
                              <Youtube className="w-8 h-8 mb-1" />
                              <p className="text-xs text-center">No YT thumb</p>
                            </div>
                          )}
                        </div>
                        
                        {/* Video */}
                        <div>
                          <p className="text-xs text-gray-400 mb-1 text-center font-mono">Video</p>
                          {output.video_path ? (
                            <div className="aspect-[9/16] bg-black rounded-[7px] overflow-hidden border border-gray-100">
                              <video
                                key={output.video_path}
                                src={output.video_path}
                                className="w-full h-full"
                                style={{ objectFit: 'contain' }}
                                controls
                                playsInline
                                preload="auto"
                                controlsList="nodownload"
                              >
                                <source src={output.video_path} type="video/mp4" />
                                Your browser does not support the video tag.
                              </video>
                            </div>
                          ) : (
                            <div className="aspect-[9/16] bg-gray-50 rounded-[7px] flex flex-col items-center justify-center text-gray-300 p-2 border border-gray-100">
                              <Play className="w-8 h-8 mb-1" />
                              <p className="text-xs text-center">No video</p>
                            </div>
                          )}
                        </div>
                      </div>
                      
                      {/* Right side: Title + Content Lines for this brand */}
                      <div className="bg-gray-50 rounded-[7px] p-4 border border-gray-100">
                        {/* Per-brand title */}
                        <div className="mb-3 pb-3 border-b border-gray-100">
                          {editingTitleBrand === brand ? (
                            <div className="flex items-start gap-2">
                              <textarea
                                value={editingTitleValue}
                                onChange={(e) => setEditingTitleValue(e.target.value)}
                                rows={2}
                                className="flex-1 px-2 py-1.5 text-sm border border-gray-200 rounded-[5px] bg-white text-gray-900 focus:ring-2 focus:ring-teal-500 focus:border-transparent resize-none"
                                autoFocus
                                onKeyDown={(e) => {
                                  if (e.key === 'Enter' && !e.shiftKey) {
                                    e.preventDefault()
                                    saveBrandTitle()
                                  }
                                  if (e.key === 'Escape') setEditingTitleBrand(null)
                                }}
                              />
                              <button
                                onClick={saveBrandTitle}
                                disabled={savingTitle}
                                className="p-1.5 rounded hover:bg-green-50 text-green-600"
                                title="Save title"
                              >
                                {savingTitle ? (
                                  <Loader2 className="w-4 h-4 animate-spin" />
                                ) : (
                                  <Save className="w-4 h-4" />
                                )}
                              </button>
                              <button
                                onClick={() => setEditingTitleBrand(null)}
                                className="p-1.5 rounded hover:bg-gray-100 text-gray-400"
                                title="Cancel"
                              >
                                <X className="w-4 h-4" />
                              </button>
                            </div>
                          ) : (
                            <div className="flex items-start justify-between gap-2">
                              <p className="text-sm font-semibold text-gray-900 flex-1">
                                {formatDisplayTitle(output.title || job.title)}
                              </p>
                              {(isCompleted || isScheduled) && (
                                <button
                                  onClick={() => startEditingTitle(brand)}
                                  className="p-1 rounded hover:bg-gray-100 text-gray-400 hover:text-gray-600 flex-shrink-0"
                                  title="Edit title for this brand"
                                >
                                  <Pencil className="w-3.5 h-3.5" />
                                </button>
                              )}
                            </div>
                          )}
                        </div>
                        
                        <div className="flex items-center justify-between mb-3">
                          <span className="text-sm font-medium text-gray-500 font-mono">Content (this brand)</span>
                          <button
                            onClick={() => copyToClipboard(
                              (output.content_lines || job.content_lines || []).join('\n'), 
                              'Content'
                            )}
                            className="p-1.5 rounded hover:bg-gray-100"
                            title="Copy content"
                          >
                            <Copy className="w-4 h-4 text-gray-400" />
                          </button>
                        </div>
                        <div className="space-y-2 max-h-[400px] overflow-y-auto">
                          {isTextVideo ? (
                            /* Text-video: display as flowing paragraph, no numbering */
                            <div className="text-sm text-gray-700 py-2 px-3 bg-white rounded-[5px] border-l-[3px] border-teal-500 whitespace-pre-line">
                              {(output.content_lines || job.content_lines || []).join('\n')}
                            </div>
                          ) : (
                            (output.content_lines || job.content_lines || []).map((line, idx) => (
                              <div 
                                key={idx} 
                                className="text-sm text-gray-700 py-1.5 px-2 bg-white rounded-[5px] border-l-[3px] border-teal-500"
                              >
                                <span className="font-medium text-gray-400 mr-2">{idx + 1}.</span>
                                {line}
                              </div>
                            ))
                          )}
                        </div>
                      </div>
                    </div>
                    
                    {/* AI Prompt Details (text-video only) */}
                    {isTextVideo && job.text_video_data && (
                      <div className="bg-gray-50 rounded-[7px] border border-gray-100 overflow-hidden">
                        <button
                          onClick={() => setShowPromptDetails(!showPromptDetails)}
                          className="w-full flex items-center justify-between px-4 py-3 text-sm font-medium text-gray-600 hover:bg-gray-100/50 transition-colors"
                        >
                          <div className="flex items-center gap-2">
                            <span className="text-xs font-mono bg-violet-100 text-violet-600 px-2 py-0.5 rounded-[3px]">AI</span>
                            <span>DeepSeek & DeAPI Prompt Details</span>
                          </div>
                          {showPromptDetails ? <ChevronUp className="w-4 h-4" /> : <ChevronDown className="w-4 h-4" />}
                        </button>
                        {showPromptDetails && (
                          <div className="px-4 pb-4 space-y-4 border-t border-gray-100">
                            {/* DeepSeek Response */}
                            {(job.text_video_data as any).deepseek_response && (
                              <div className="mt-3">
                                <p className="text-xs font-medium text-teal-600 mb-1.5">DeepSeek Full Response:</p>
                                <pre className="text-xs text-gray-600 bg-white rounded-[5px] p-3 overflow-x-auto whitespace-pre-wrap max-h-[300px] overflow-y-auto font-mono border border-gray-100">
                                  {(job.text_video_data as any).deepseek_response}
                                </pre>
                              </div>
                            )}
                            {/* Image AI Prompts (sent to DeAPI) */}
                            {((job.text_video_data as any).images || []).length > 0 && (
                              <div>
                                <p className="text-xs font-medium text-green-600 mb-1.5">DeAPI Image Prompts (Flux1schnell):</p>
                                <div className="space-y-2">
                                  {((job.text_video_data as any).images as { query: string; source_type: string }[]).map((img, idx) => (
                                    <div key={idx} className="text-xs bg-white rounded-[5px] p-2.5 border-l-[3px] border-green-500 border border-gray-100">
                                      <span className="text-green-600 font-medium">Image {idx + 1}:</span>
                                      <span className="text-gray-600 ml-2">{img.query}</span>
                                    </div>
                                  ))}
                                </div>
                              </div>
                            )}
                            {/* Thumbnail Image Prompt */}
                            {(job.text_video_data as any).thumbnail_image?.query && (
                              <div>
                                <p className="text-xs font-medium text-amber-600 mb-1.5">Thumbnail Image Prompt:</p>
                                <div className="text-xs bg-white rounded-[5px] p-2.5 border-l-[3px] border-amber-500 border border-gray-100 text-gray-600">
                                  {(job.text_video_data as any).thumbnail_image.query}
                                </div>
                              </div>
                            )}
                          </div>
                        )}
                      </div>
                    )}
                    
                    {/* Caption */}
                    {output.caption && (
                      <div className="space-y-4">
                        {/* Instagram Caption */}
                        <div className="bg-white rounded-[7px] p-4 border border-gray-100">
                          <div className="flex items-center justify-between mb-2">
                            <div className="flex items-center gap-2">
                              <span className="w-2.5 h-2.5 rounded-full bg-gradient-to-br from-purple-500 via-pink-500 to-orange-400" />
                              <span className="text-sm font-medium text-gray-700">Instagram Caption</span>
                            </div>
                            <button
                              onClick={() => copyToClipboard(output.caption!, 'Instagram Caption')}
                              className="p-1.5 rounded hover:bg-gray-50"
                            >
                              <Copy className="w-4 h-4 text-gray-400" />
                            </button>
                          </div>
                          <div className="max-h-[300px] overflow-y-auto">
                            <p className="text-sm text-gray-600 whitespace-pre-line">
                              {output.caption}
                            </p>
                          </div>
                        </div>
                        
                        {/* Facebook Caption */}
                        <div className="bg-white rounded-[7px] p-4 border border-gray-100">
                          <div className="flex items-center justify-between mb-2">
                            <div className="flex items-center gap-2">
                              <span className="w-2.5 h-2.5 rounded-full bg-blue-600" />
                              <span className="text-sm font-medium text-gray-700">Facebook Caption</span>
                              <span className="text-xs text-gray-400">(shorter)</span>
                            </div>
                            <button
                              onClick={() => copyToClipboard(createFacebookCaption(output.caption!), 'Facebook Caption')}
                              className="p-1.5 rounded hover:bg-gray-50"
                            >
                              <Copy className="w-4 h-4 text-gray-400" />
                            </button>
                          </div>
                          <div className="max-h-[200px] overflow-y-auto">
                            <p className="text-sm text-gray-600 whitespace-pre-line">
                              {createFacebookCaption(output.caption!)}
                            </p>
                          </div>
                        </div>
                        
                        {/* YouTube Title & Description */}
                        <div className="bg-white rounded-[7px] p-4 border border-gray-100">
                          <div className="flex items-center justify-between mb-2">
                            <div className="flex items-center gap-2">
                              <span className="w-2.5 h-2.5 rounded-full bg-red-600" />
                              <span className="text-sm font-medium text-gray-700">YouTube Shorts</span>
                            </div>
                          </div>
                          
                          {/* YouTube Title */}
                          <div className="mb-3">
                            <div className="flex items-center justify-between mb-1">
                              <span className="text-xs font-medium text-gray-500 font-mono">Title</span>
                              <button
                                onClick={() => copyToClipboard(output.yt_title || job.title, 'YouTube Title')}
                                className="p-1 rounded hover:bg-gray-50"
                              >
                                <Copy className="w-3.5 h-3.5 text-gray-400" />
                              </button>
                            </div>
                            <p className="text-sm font-medium text-gray-900 bg-gray-50 rounded-[5px] px-2 py-1.5">
                              {output.yt_title || job.title}
                            </p>
                          </div>
                          
                          {/* YouTube Description (same as Facebook) */}
                          <div>
                            <div className="flex items-center justify-between mb-1">
                              <span className="text-xs font-medium text-gray-500 font-mono">Description</span>
                              <button
                                onClick={() => copyToClipboard(createFacebookCaption(output.caption!), 'YouTube Description')}
                                className="p-1 rounded hover:bg-gray-50"
                              >
                                <Copy className="w-3.5 h-3.5 text-gray-400" />
                              </button>
                            </div>
                            <div className="max-h-[120px] overflow-y-auto bg-gray-50 rounded-[5px] px-2 py-1.5">
                              <p className="text-sm text-gray-600 whitespace-pre-line">
                                {createFacebookCaption(output.caption!)}
                              </p>
                            </div>
                          </div>
                        </div>
                      </div>
                    )}
                    
                    {/* Scheduled Info */}
                    {isScheduled && output.scheduled_time && (
                      <div className="bg-teal-50 rounded-[7px] p-4 flex items-center gap-3 border border-teal-100">
                        <Check className="w-5 h-5 text-teal-600" />
                        <div>
                          <p className="font-medium text-teal-700">Scheduled</p>
                          <p className="text-sm text-teal-600">
                            {format(new Date(output.scheduled_time), 'MMMM d, yyyy h:mm a')}
                          </p>
                        </div>
                      </div>
                    )}
                    
                    {/* Actions */}
                    <div className="flex gap-2">
                      <button
                        onClick={() => handleDownload(brand, output)}
                        className="flex-1 flex items-center justify-center gap-2 px-4 py-2 text-sm font-medium text-gray-500 bg-white border border-gray-200 rounded-[7px] hover:bg-gray-50 hover:text-gray-700 transition-colors"
                      >
                        <Download className="w-4 h-4" />
                        Download
                      </button>
                      
                      {isCompleted && (
                        <>
                          <button
                            onClick={() => openBrandScheduleModal(brand)}
                            disabled={schedulingBrand === brand || isGenerating}
                            className="flex-1 flex items-center justify-center gap-2 px-4 py-2 text-sm font-semibold text-white bg-green-600 rounded-[7px] hover:brightness-110 shadow-sm transition disabled:opacity-50"
                          >
                            {schedulingBrand === brand ? (
                              <Loader2 className="w-4 h-4 animate-spin" />
                            ) : (
                              <Calendar className="w-4 h-4" />
                            )}
                            Schedule
                          </button>
                          
                          <button
                            onClick={() => handleRegenerateBrand(brand)}
                            disabled={regenerateBrand.isPending || isGenerating}
                            className="flex items-center justify-center px-3 py-2 text-sm font-medium text-gray-400 bg-white border border-gray-200 rounded-[7px] hover:bg-gray-50 hover:text-gray-600 transition-colors disabled:opacity-50"
                          >
                            <RefreshCw className="w-4 h-4" />
                          </button>
                        </>
                      )}
                      
                      {isScheduled && (
                        <>
                          <button
                            onClick={() => copyToClipboard(output.caption || '', 'Caption')}
                            className="flex-1 flex items-center justify-center gap-2 px-4 py-2 text-sm font-medium text-gray-500 bg-white border border-gray-200 rounded-[7px] hover:bg-gray-50 hover:text-gray-700 transition-colors"
                          >
                            <Copy className="w-4 h-4" />
                            Copy Caption
                          </button>
                          <button
                            onClick={() => copyToClipboard(job.title || '', 'Title')}
                            className="flex-1 flex items-center justify-center gap-2 px-4 py-2 text-sm font-medium text-gray-500 bg-white border border-gray-200 rounded-[7px] hover:bg-gray-50 hover:text-gray-700 transition-colors"
                          >
                            <Copy className="w-4 h-4" />
                            Copy Title
                          </button>
                        </>
                      )}
                    </div>
                  </div>
                ) : (
                  <div className="text-center py-8 text-gray-500">
                    Waiting to generate...
                  </div>
                )}
              </div>
            </div>
          )
        })}
      </div>
      
      {/* Delete Modal */}
      <Modal
        isOpen={deleteModalOpen}
        onClose={() => setDeleteModalOpen(false)}
        title="Delete Job"
        size="sm"
      >
        <div className="space-y-4">
          <p className="text-gray-500">
            Are you sure you want to delete this job? This will also delete all generated media.
          </p>
          <div className="flex gap-3">
            <button
              onClick={() => setDeleteModalOpen(false)}
              className="flex-1 px-4 py-2 text-sm font-medium text-gray-500 bg-white border border-gray-200 rounded-[7px] hover:bg-gray-50 transition-colors"
            >
              Cancel
            </button>
            <button
              onClick={handleDelete}
              disabled={deleteJob.isPending}
              className="flex-1 px-4 py-2 text-sm font-semibold text-white bg-rose-600 rounded-[7px] hover:brightness-110 shadow-sm transition disabled:opacity-50"
            >
              {deleteJob.isPending ? (
                <Loader2 className="w-4 h-4 animate-spin" />
              ) : (
                'Delete'
              )}
            </button>
          </div>
        </div>
      </Modal>
      
      {/* Edit Title Modal */}
      <Modal
        isOpen={editTitleModalOpen}
        onClose={() => setEditTitleModalOpen(false)}
        title="Edit Title"
        size="md"
      >
        <div className="space-y-4">
          <div>
            <label className="block text-sm font-medium text-gray-700 mb-2">
              New Title
            </label>
            <textarea
              value={editedTitle}
              onChange={(e) => setEditedTitle(e.target.value)}
              rows={4}
              className="w-full px-3 py-2 text-sm bg-white border border-gray-200 rounded-[7px] text-gray-900 placeholder-gray-400 focus:ring-2 focus:ring-teal-500 focus:border-transparent resize-none"
              placeholder="Enter new title..."
            />
          </div>
          <p className="text-sm text-gray-400">
            Changing the title will regenerate all brand images with the new text.
          </p>
          <div className="flex gap-3">
            <button
              onClick={() => setEditTitleModalOpen(false)}
              className="flex-1 px-4 py-2 text-sm font-medium text-gray-500 bg-white border border-gray-200 rounded-[7px] hover:bg-gray-50 transition-colors"
            >
              Cancel
            </button>
            <button
              onClick={handleSaveTitle}
              disabled={updateJob.isPending || !editedTitle.trim()}
              className="flex-1 px-4 py-2 text-sm font-semibold text-white bg-teal-600 rounded-[7px] hover:brightness-110 shadow-sm transition disabled:opacity-50"
            >
              {updateJob.isPending ? (
                <Loader2 className="w-4 h-4 animate-spin" />
              ) : (
                'Save & Regenerate'
              )}
            </button>
          </div>
        </div>
      </Modal>
      
      {/* Per-brand Schedule Options Modal */}
      {brandScheduleModalBrand && (
        <Modal
          isOpen={!!brandScheduleModalBrand}
          onClose={() => setBrandScheduleModalBrand(null)}
          title={`Schedule — ${brandScheduleModalBrand ? getBrandLabel(brandScheduleModalBrand) : ''}`}
          size="md"
        >
          <div className="space-y-4">
            {/* Mode selection */}
            <div className="grid grid-cols-2 gap-3">
              <button
                onClick={() => setBrandScheduleMode('auto')}
                className={`flex flex-col items-center gap-2 p-4 rounded-[10px] border-2 transition-all ${
                  brandScheduleMode === 'auto'
                    ? 'border-teal-500 bg-teal-50'
                    : 'border-gray-200 hover:border-gray-300 bg-white'
                }`}
              >
                <Calendar className={`w-5 h-5 ${brandScheduleMode === 'auto' ? 'text-teal-600' : 'text-gray-400'}`} />
                <span className={`text-sm font-medium ${brandScheduleMode === 'auto' ? 'text-teal-700' : 'text-gray-500'}`}>
                  Schedule Now
                </span>
                <span className="text-[10px] text-gray-400 text-center">Next available time</span>
              </button>
              <button
                onClick={() => setBrandScheduleMode('custom')}
                className={`flex flex-col items-center gap-2 p-4 rounded-[10px] border-2 transition-all ${
                  brandScheduleMode === 'custom'
                    ? 'border-teal-500 bg-teal-50'
                    : 'border-gray-200 hover:border-gray-300 bg-white'
                }`}
              >
                <Clock className={`w-5 h-5 ${brandScheduleMode === 'custom' ? 'text-teal-600' : 'text-gray-400'}`} />
                <span className={`text-sm font-medium ${brandScheduleMode === 'custom' ? 'text-teal-700' : 'text-gray-500'}`}>
                  Custom Time
                </span>
                <span className="text-[10px] text-gray-400 text-center">Pick date & time</span>
              </button>
            </div>

            {/* Custom date/time picker */}
            {brandScheduleMode === 'custom' && (
              <div className="grid grid-cols-2 gap-4">
                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-1">Date</label>
                  <input
                    type="date"
                    value={brandCustomDate}
                    min={new Date().toISOString().split('T')[0]}
                    onChange={(e) => setBrandCustomDate(e.target.value)}
                    className="w-full px-3 py-2 text-sm bg-white border border-gray-200 rounded-[7px] text-gray-900 focus:ring-2 focus:ring-teal-500 focus:border-transparent"
                  />
                </div>
                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-1">Time</label>
                  <input
                    type="time"
                    value={brandCustomTime}
                    onChange={(e) => setBrandCustomTime(e.target.value)}
                    className="w-full px-3 py-2 text-sm bg-white border border-gray-200 rounded-[7px] text-gray-900 focus:ring-2 focus:ring-teal-500 focus:border-transparent"
                  />
                </div>
              </div>
            )}

            {/* Confirm */}
            <div className="flex gap-3 pt-2">
              <button
                onClick={() => setBrandScheduleModalBrand(null)}
                className="flex-1 px-4 py-2 text-sm font-medium text-gray-500 bg-white border border-gray-200 rounded-[7px] hover:bg-gray-50 transition-colors"
              >
                Cancel
              </button>
              <button
                onClick={confirmBrandSchedule}
                disabled={brandScheduleMode === 'custom' && (!brandCustomDate || !brandCustomTime)}
                className="flex-1 flex items-center justify-center gap-2 px-4 py-2 text-sm font-semibold text-white bg-teal-600 rounded-[7px] hover:brightness-110 shadow-sm transition disabled:opacity-50"
              >
                <Calendar className="w-4 h-4" />
                {brandScheduleMode === 'auto' ? 'Schedule Now' : 'Schedule'}
              </button>
            </div>
          </div>
        </Modal>
      )}

      {/* Custom Schedule Modal */}
      <Modal
        isOpen={customScheduleModalOpen}
        onClose={() => setCustomScheduleModalOpen(false)}
        title="Custom Schedule"
        size="md"
      >
        <div className="space-y-4">
          <p className="text-gray-500">
            Choose a date and time to schedule {completedCount === 1 ? 'this brand' : scheduledCount > 0 ? `the ${completedCount} remaining brands` : `all ${completedCount} brands`}.
            {completedCount > 1 && 'Brands will be staggered by 1 hour each.'}
          </p>
          
          <div className="grid grid-cols-2 gap-4">
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-2">
                Date
              </label>
              <input
                type="date"
                value={customScheduleDate}
                onChange={(e) => setCustomScheduleDate(e.target.value)}
                min={new Date().toISOString().split('T')[0]}
                className="w-full px-3 py-2 text-sm bg-white border border-gray-200 rounded-[7px] text-gray-900 focus:ring-2 focus:ring-teal-500 focus:border-transparent"
              />
            </div>
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-2">
                Start Time
              </label>
              <input
                type="time"
                value={customScheduleTime}
                onChange={(e) => setCustomScheduleTime(e.target.value)}
                className="w-full px-3 py-2 text-sm bg-white border border-gray-200 rounded-[7px] text-gray-900 focus:ring-2 focus:ring-teal-500 focus:border-transparent"
              />
            </div>
          </div>
          
          {isCustomScheduleInPast && (
            <p className="text-sm text-red-500">Cannot schedule in the past. Please select a future date and time.</p>
          )}

          {customScheduleDate && customScheduleTime && !isCustomScheduleInPast && completedCount > 0 && (
            <div className="bg-gray-50 p-3 rounded-[7px] text-sm text-gray-600 border border-gray-100">
              <p className="font-medium mb-1 text-gray-900">Schedule Preview:</p>
              <ul className="space-y-1">
                {Object.entries(job?.brand_outputs || {})
                  .filter(([_, output]) => output.status === 'completed')
                  .map(([brand], index) => {
                    const baseTime = new Date(`${customScheduleDate}T${customScheduleTime}`)
                    baseTime.setHours(baseTime.getHours() + index)
                    return (
                      <li key={brand} className="flex items-center gap-2">
                        <span className="capitalize">{brand}</span>
                        <span className="text-gray-300">→</span>
                        <span>{format(baseTime, 'MMM d, h:mm a')}</span>
                      </li>
                    )
                  })}
              </ul>
            </div>
          )}
          
          <div className="flex gap-3">
            <button
              onClick={() => setCustomScheduleModalOpen(false)}
              className="flex-1 px-4 py-2 text-sm font-medium text-gray-500 bg-white border border-gray-200 rounded-[7px] hover:bg-gray-50 transition-colors"
            >
              Cancel
            </button>
            <button
              onClick={handleCustomScheduleAll}
              disabled={schedulingCustom || !customScheduleDate || !customScheduleTime || isCustomScheduleInPast}
              className="flex-1 flex items-center justify-center gap-2 px-4 py-2 text-sm font-semibold text-white bg-teal-600 rounded-[7px] hover:brightness-110 shadow-sm transition disabled:opacity-50"
            >
              {schedulingCustom ? (
                <Loader2 className="w-4 h-4 animate-spin" />
              ) : (
                <>
                  <CalendarClock className="w-4 h-4" />
                  {scheduleButtonLabel}
                </>
              )}
            </button>
          </div>
        </div>
      </Modal>
    </div>
  )
}
