import { useState } from 'react'
import { useParams, useNavigate } from 'react-router-dom'
import { 
  ArrowLeft,
  RefreshCw,
  Trash2,
  Download,
  Calendar,
  Edit2,
  Copy,
  Play,
  Loader2,
  AlertCircle,
  Check,
  Clock,
  CalendarClock,
  Youtube,
  Pencil,
  Save,
  X,
} from 'lucide-react'
import toast from 'react-hot-toast'
import { format } from 'date-fns'
import { 
  useJob, 
  useDeleteJob, 
  useRegenerateJob, 
  useRegenerateBrand,
  useUpdateJob,
  useJobNextSlots,
  useUpdateBrandStatus,
  useUpdateBrandContent,
  useRetryJob
} from '@/features/jobs'
import { useAutoScheduleReel } from '@/features/scheduling'
import { BrandBadge, getBrandLabel, getBrandColor } from '@/features/brands'
import { StatusBadge, JobDetailSkeleton, Modal } from '@/shared/components'
import { createFacebookCaption } from '@/shared/lib/captionUtils'
import { PostJobDetail } from './PostJobDetail'
import type { BrandName, BrandOutput } from '@/shared/types'

export function JobDetailPage() {
  const { jobId } = useParams<{ jobId: string }>()
  const navigate = useNavigate()
  const id = jobId || ''
  
  const { data: job, isLoading, error, refetch } = useJob(id)
  const { data: nextSlots } = useJobNextSlots(id)
  const deleteJob = useDeleteJob()
  const regenerateJob = useRegenerateJob()
  const regenerateBrand = useRegenerateBrand()
  const updateJob = useUpdateJob()
  const updateBrandStatus = useUpdateBrandStatus()
  const updateBrandContent = useUpdateBrandContent()
  const autoSchedule = useAutoScheduleReel()
  const retryJob = useRetryJob()
  
  // Modal states
  const [deleteModalOpen, setDeleteModalOpen] = useState(false)
  const [editTitleModalOpen, setEditTitleModalOpen] = useState(false)
  const [editedTitle, setEditedTitle] = useState('')
  const [customScheduleModalOpen, setCustomScheduleModalOpen] = useState(false)
  const [customScheduleDate, setCustomScheduleDate] = useState('')
  const [customScheduleTime, setCustomScheduleTime] = useState('')
  
  // Loading states
  const [schedulingBrand, setSchedulingBrand] = useState<BrandName | null>(null)
  const [schedulingAll, setSchedulingAll] = useState(false)
  const [schedulingCustom, setSchedulingCustom] = useState(false)

  // Per-brand title editing state
  const [editingTitleBrand, setEditingTitleBrand] = useState<string | null>(null)
  const [editingTitleValue, setEditingTitleValue] = useState('')
  const [savingTitle, setSavingTitle] = useState(false)

  // Per-brand schedule modal state
  const [brandScheduleModalBrand, setBrandScheduleModalBrand] = useState<BrandName | null>(null)
  const [brandScheduleMode, setBrandScheduleMode] = useState<'auto' | 'custom'>('auto')
  const [brandCustomDate, setBrandCustomDate] = useState('')
  const [brandCustomTime, setBrandCustomTime] = useState('')
  
  const isGenerating = job?.status === 'generating' || job?.status === 'pending'

  // Detect auto-generated jobs: fixed_title is false/undefined AND multiple brands
  // This works even while brands are still generating (before per-brand titles appear)
  const isAutoGenerated = job ? !job.fixed_title && (job.brands?.length || 0) > 1 : false

  // Per-brand title helpers
  const startEditingTitle = (brand: string) => {
    const output = job?.brand_outputs?.[brand as BrandName]
    setEditingTitleValue(output?.title || job?.title || '')
    setEditingTitleBrand(brand)
  }

  const saveBrandTitle = async () => {
    if (!editingTitleBrand || !job) return
    setSavingTitle(true)
    try {
      await updateBrandContent.mutateAsync({
        id: job.id,
        brand: editingTitleBrand as BrandName,
        data: { title: editingTitleValue },
      })
      toast.success('Title updated!')
      setEditingTitleBrand(null)
      refetch()
    } catch {
      toast.error('Failed to update title')
    } finally {
      setSavingTitle(false)
    }
  }
  
  const allScheduled = job ? Object.entries(job.brand_outputs || {})
    .filter(([_, output]) => output.status === 'completed' || output.status === 'scheduled')
    .every(([_, output]) => output.status === 'scheduled') : false
  
  // Dismiss a brand — mark it so it's excluded from Schedule All
  const handleDismissBrand = async (brand: BrandName) => {
    if (!job) return
    try {
      await updateBrandStatus.mutateAsync({ id, brand, status: 'dismissed' })
      toast.success(`${getBrandLabel(brand)} removed from scheduling`)
      refetch()
    } catch {
      toast.error('Failed to dismiss brand')
    }
  }

  // Restore a dismissed brand back to completed
  const handleRestoreBrand = async (brand: BrandName) => {
    if (!job) return
    try {
      await updateBrandStatus.mutateAsync({ id, brand, status: 'completed' })
      toast.success(`${getBrandLabel(brand)} restored`)
      refetch()
    } catch {
      toast.error('Failed to restore brand')
    }
  }
  
  const handleDelete = async () => {
    try {
      await deleteJob.mutateAsync(id)
      toast.success('Job deleted')
      navigate('/history')
    } catch {
      toast.error('Failed to delete job')
    }
  }
  
  const handleRegenerateAll = async () => {
    try {
      await regenerateJob.mutateAsync(id)
      toast.success('Regeneration started')
      refetch()
    } catch {
      toast.error('Failed to regenerate')
    }
  }
  
  const handleRegenerateBrand = async (brand: BrandName) => {
    try {
      await regenerateBrand.mutateAsync({ id, brand })
      toast.success(`Regenerating ${getBrandLabel(brand)}`)
      refetch()
    } catch {
      toast.error('Failed to regenerate')
    }
  }
  
  const openEditTitleModal = () => {
    setEditedTitle(job?.title || '')
    setEditTitleModalOpen(true)
  }
  
  const handleSaveTitle = async () => {
    if (!editedTitle.trim()) {
      toast.error('Title cannot be empty')
      return
    }
    
    try {
      await updateJob.mutateAsync({ id, data: { title: editedTitle } })
      setEditTitleModalOpen(false)
      toast.success('Title updated')
      await regenerateJob.mutateAsync(id)
      toast.success('Regenerating with new title')
      refetch()
    } catch {
      toast.error('Failed to update title')
    }
  }
  
  const openBrandScheduleModal = (brand: BrandName) => {
    setBrandScheduleModalBrand(brand)
    setBrandScheduleMode('auto')
    const tomorrow = new Date()
    tomorrow.setDate(tomorrow.getDate() + 1)
    setBrandCustomDate(tomorrow.toISOString().split('T')[0])
    setBrandCustomTime('12:00')
  }

  const confirmBrandSchedule = () => {
    if (!brandScheduleModalBrand || !job) return
    const output = job.brand_outputs?.[brandScheduleModalBrand]
    if (!output) return

    let customTime: string | undefined
    if (brandScheduleMode === 'custom' && brandCustomDate && brandCustomTime) {
      const dt = new Date(`${brandCustomDate}T${brandCustomTime}:00`)
      if (dt <= new Date()) {
        toast.error('Please select a future date and time')
        return
      }
      customTime = dt.toISOString()
    }

    const brand = brandScheduleModalBrand
    setBrandScheduleModalBrand(null)
    handleScheduleBrand(brand, output, customTime)
  }

  const handleScheduleBrand = async (brand: BrandName, output: BrandOutput, customScheduleTime?: string) => {
    if (!output.reel_id || !job) {
      toast.error('No reel to schedule')
      return
    }
    
    const caption = output.caption || `${job.title}\n\nGenerated content for ${brand}`
    
    setSchedulingBrand(brand)
    try {
      await autoSchedule.mutateAsync({
        brand,
        reel_id: output.reel_id,
        variant: job.variant,
        caption: caption,
        yt_title: output.yt_title,
        yt_thumbnail_path: output.yt_thumbnail_path,
        video_path: output.video_path,
        thumbnail_path: output.thumbnail_path,
        platforms: job.platforms,
        ...(customScheduleTime ? { scheduled_time: customScheduleTime } : {}),
      })
      
      await updateBrandStatus.mutateAsync({
        id,
        brand,
        status: 'scheduled',
      })
      
      toast.success(`${getBrandLabel(brand)} scheduled!`)
      refetch()
    } catch {
      toast.error('Failed to schedule')
    } finally {
      setSchedulingBrand(null)
    }
  }
  
  const handleScheduleAll = async () => {
    if (!job) return
    
    const completedBrands = Object.entries(job.brand_outputs || {})
      .filter(([_, output]) => output.status === 'completed')
      .map(([brand]) => brand as BrandName)
    
    if (completedBrands.length === 0) {
      toast.error('No completed brands to schedule')
      return
    }
    
    setSchedulingAll(true)
    let scheduled = 0
    let failed = 0
    
    for (const brand of completedBrands) {
      const output = job.brand_outputs[brand]
      if (output?.reel_id) {
        try {
          const caption = output.caption || `${job.title}\n\nGenerated content for ${brand}`
          
          await autoSchedule.mutateAsync({
            brand,
            reel_id: output.reel_id,
            variant: job.variant,
            caption: caption,
            yt_title: output.yt_title,  // Pass YouTube title for YT Shorts
            yt_thumbnail_path: output.yt_thumbnail_path,  // Clean AI image for YouTube
            video_path: output.video_path,
            thumbnail_path: output.thumbnail_path,
            platforms: job.platforms,  // Pass platforms from job
          })
          await updateBrandStatus.mutateAsync({
            id,
            brand,
            status: 'scheduled',
          })
          scheduled++
        } catch (error) {
          console.error(`Failed to schedule ${brand}:`, error)
          failed++
        }
      }
    }
    
    setSchedulingAll(false)
    
    if (scheduled > 0) {
      const message = failed > 0 
        ? `✅ ${scheduled} brand${scheduled !== 1 ? 's' : ''} scheduled! ${failed} failed.`
        : scheduled === 1
          ? '🎉 Reel scheduled successfully!'
          : `🎉 All ${scheduled} brands scheduled successfully!`
      
      toast.success(message, { duration: 4000 })
      
      setTimeout(() => {
        navigate('/calendar')
      }, 1500)
    } else if (failed > 0) {
      toast.error('Failed to schedule brands')
    }
  }
  
  const openCustomScheduleModal = () => {
    // Set default to tomorrow at 10:00
    const tomorrow = new Date()
    tomorrow.setDate(tomorrow.getDate() + 1)
    setCustomScheduleDate(tomorrow.toISOString().split('T')[0])
    setCustomScheduleTime('10:00')
    setCustomScheduleModalOpen(true)
  }
  
  const handleCustomScheduleAll = async () => {
    if (!job || !customScheduleDate || !customScheduleTime) {
      toast.error('Please select a date and time')
      return
    }
    
    const completedBrands = Object.entries(job.brand_outputs || {})
      .filter(([_, output]) => output.status === 'completed')
      .map(([brand]) => brand as BrandName)
    
    if (completedBrands.length === 0) {
      toast.error('No completed brands to schedule')
      return
    }
    
    setSchedulingCustom(true)
    let scheduled = 0
    let failed = 0
    
    // Parse base datetime
    const baseDateTime = new Date(`${customScheduleDate}T${customScheduleTime}`)
    
    for (let i = 0; i < completedBrands.length; i++) {
      const brand = completedBrands[i]
      const output = job.brand_outputs[brand]
      if (output?.reel_id) {
        try {
          const caption = output.caption || `${job.title}\n\nGenerated content for ${brand}`
          
          // Stagger brands by 1 hour each
          const scheduledTime = new Date(baseDateTime)
          scheduledTime.setHours(scheduledTime.getHours() + i)
          
          await autoSchedule.mutateAsync({
            brand,
            reel_id: output.reel_id,
            variant: job.variant,
            caption: caption,
            yt_title: output.yt_title,  // Pass YouTube title for YT Shorts
            yt_thumbnail_path: output.yt_thumbnail_path,  // Clean AI image for YouTube
            video_path: output.video_path,
            thumbnail_path: output.thumbnail_path,
            scheduled_time: scheduledTime.toISOString(),
            platforms: job.platforms,  // Pass platforms from job
          })
          await updateBrandStatus.mutateAsync({
            id,
            brand,
            status: 'scheduled',
          })
          scheduled++
        } catch (error) {
          console.error(`Failed to schedule ${brand}:`, error)
          failed++
        }
      }
    }
    
    setSchedulingCustom(false)
    setCustomScheduleModalOpen(false)
    
    if (scheduled > 0) {
      const message = failed > 0 
        ? `✅ ${scheduled} brand${scheduled !== 1 ? 's' : ''} scheduled for ${customScheduleDate}! ${failed} failed.`
        : scheduled === 1
          ? `🎉 Reel scheduled for ${customScheduleDate}!`
          : `🎉 All ${scheduled} brands scheduled for ${customScheduleDate}!`
      
      toast.success(message, { duration: 4000 })
      
      setTimeout(() => {
        navigate('/calendar')
      }, 1500)
    } else if (failed > 0) {
      toast.error('Failed to schedule brands')
    }
  }
  
  const handleDownload = (_brand: BrandName, output: BrandOutput) => {
    if (output.video_path) {
      const link = document.createElement('a')
      link.href = output.video_path
      link.download = `${_brand}_${output.reel_id || 'reel'}.mp4`
      link.click()
    }
  }
  
  const copyToClipboard = (text: string, label: string) => {
    navigator.clipboard.writeText(text)
    toast.success(`${label} copied!`)
  }
  
  if (isLoading) return <JobDetailSkeleton />
  
  if (error || !job) {
    return (
      <div className="text-center py-12">
        <AlertCircle className="w-12 h-12 text-red-500 mx-auto mb-4" />
        <h2 className="text-xl font-semibold text-gray-900 mb-2">Job not found</h2>
        <button onClick={() => navigate('/history')} className="btn btn-primary mt-4">
          Back to Jobs
        </button>
      </div>
    )
  }

  // Delegate to post-specific detail view
  if (job.variant === 'post') {
    return <PostJobDetail job={job} refetch={refetch} />
  }
  
  const completedCount = Object.values(job.brand_outputs || {})
    .filter(o => o.status === 'completed').length
  const dismissedCount = Object.values(job.brand_outputs || {})
    .filter(o => o.status === 'dismissed').length
  const scheduledCount = Object.values(job.brand_outputs || {})
    .filter(o => o.status === 'scheduled').length
  const scheduleButtonLabel = completedCount === 1 ? 'Schedule Reel' : scheduledCount > 0 ? `Schedule ${completedCount} Remaining` : `Schedule All (${completedCount})`
  
  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="flex items-start justify-between">
        <div className="flex items-start gap-4">
          <button
            onClick={() => navigate('/history')}
            className="p-2 rounded-lg hover:bg-gray-100"
          >
            <ArrowLeft className="w-5 h-5" />
          </button>
          <div>
            <div className="flex items-center gap-3 mb-2">
              <span className="text-sm font-mono text-gray-400">#{job.id}</span>
              <StatusBadge status={job.status} size="md" />
            </div>
            {isAutoGenerated ? (
              /* Auto-generated: compact header, per-brand content shown in cards below */
              <>
                <h1 className="text-lg font-bold text-gray-900">
                  🤖 Auto-Generated Viral Reels
                </h1>
                <p className="text-gray-500 text-sm mt-1">
                  {job.brands.length} brand{job.brands.length !== 1 ? 's' : ''} · each with unique title & content
                  {dismissedCount > 0 && <span className="text-gray-400"> · {dismissedCount} dismissed</span>}
                </p>
                <p className="text-gray-400 text-xs mt-1">
                  Created {format(new Date(job.created_at), 'MMMM d, yyyy h:mm a')}
                </p>
              </>
            ) : (
              /* Manual generate: shared title & content */
              <>
                <h1 className="text-2xl font-bold text-gray-900 whitespace-pre-line">
                  {job.title}
                </h1>
                <p className="text-gray-500 text-sm mt-2">
                  Created {format(new Date(job.created_at), 'MMMM d, yyyy h:mm a')}
                </p>
                
                {/* Content Lines - show for shared-title jobs */}
                {job.content_lines && job.content_lines.length > 0 && (
                  <div className="mt-3 text-sm text-gray-600 bg-gray-50 rounded-lg p-3">
                    <p className="font-medium text-gray-700 mb-1">Content:</p>
                    <ul className="list-disc list-inside space-y-0.5">
                      {job.content_lines.map((line, idx) => (
                        <li key={idx}>{line}</li>
                      ))}
                    </ul>
                  </div>
                )}
                
                {/* AI Prompt - show if dark mode */}
                {job.variant === 'dark' && job.ai_prompt && (
                  <div className="mt-2 text-sm text-gray-600 bg-purple-50 rounded-lg p-3">
                    <p className="font-medium text-purple-700 mb-1">AI Background Prompt:</p>
                    <p className="text-purple-600 italic">{job.ai_prompt}</p>
                  </div>
                )}
              </>
            )}
            
            {/* Job-level error message */}
            {job.error_message && (
              <div className="mt-3 text-sm bg-red-50 border border-red-200 rounded-lg p-3">
                <div className="flex items-start gap-2">
                  <AlertCircle className="w-4 h-4 text-red-500 mt-0.5 flex-shrink-0" />
                  <div className="flex-1">
                    <p className="font-medium text-red-700">Error:</p>
                    <p className="text-red-600">{job.error_message}</p>
                  </div>
                  {job.status === 'failed' && (
                    <button
                      onClick={() => {
                        retryJob.mutate(id, {
                          onSuccess: () => toast.success('Retrying incomplete brands...'),
                          onError: (err: any) => toast.error(err?.message || 'Failed to retry job'),
                        })
                      }}
                      disabled={retryJob.isPending}
                      className="btn btn-primary btn-sm flex-shrink-0"
                    >
                      {retryJob.isPending ? (
                        <Loader2 className="w-3 h-3 animate-spin" />
                      ) : (
                        <RefreshCw className="w-3 h-3" />
                      )}
                      Retry Incomplete
                    </button>
                  )}
                </div>
              </div>
            )}
          </div>
        </div>
        
        <div className="flex items-center gap-2">
          {!isAutoGenerated && (
            <button
              onClick={openEditTitleModal}
              disabled={isGenerating || allScheduled}
              className="btn btn-secondary"
              title={allScheduled ? "Cannot edit - brands are scheduled" : ""}
            >
              <Edit2 className="w-4 h-4" />
              Edit Title
            </button>
          )}
          
          {!isGenerating && (
            <button
              onClick={handleRegenerateAll}
              disabled={regenerateJob.isPending || allScheduled}
              className="btn btn-secondary"
              title={allScheduled ? "Cannot regenerate - brands are scheduled" : ""}
            >
              {regenerateJob.isPending ? (
                <Loader2 className="w-4 h-4 animate-spin" />
              ) : (
                <RefreshCw className="w-4 h-4" />
              )}
              Regenerate All
            </button>
          )}
          
          <button
            onClick={() => setDeleteModalOpen(true)}
            disabled={isGenerating}
            className="btn btn-danger"
          >
            <Trash2 className="w-4 h-4" />
            Delete
          </button>
        </div>
      </div>
      
      {/* Quick Schedule Section */}
      {completedCount > 0 && (
        <div className="card p-4 bg-gradient-to-r from-purple-50 to-blue-50 border-purple-100">
          <div className="flex items-center justify-between">
            <div className="flex items-center gap-3">
              <Calendar className="w-5 h-5 text-purple-600" />
              <div>
                <span className="font-semibold text-gray-900">Quick Schedule</span>
                <span className="text-gray-500 ml-2">
                  {completedCount} brand{completedCount !== 1 ? 's' : ''} ready
                </span>
              </div>
            </div>
            <div className="flex items-center gap-2">
              <button
                onClick={handleScheduleAll}
                disabled={schedulingAll || schedulingCustom || isGenerating || allScheduled}
                className="btn btn-primary"
                title={allScheduled ? "All brands already scheduled" : "Schedule to next available slots"}
              >
                {schedulingAll ? (
                  <Loader2 className="w-4 h-4 animate-spin" />
                ) : allScheduled ? (
                  <Check className="w-4 h-4" />
                ) : (
                  <Calendar className="w-4 h-4" />
                )}
                {allScheduled ? 'All Scheduled' : scheduleButtonLabel}
              </button>
              
              {!allScheduled && (
                <button
                  onClick={openCustomScheduleModal}
                  disabled={schedulingAll || schedulingCustom || isGenerating}
                  className="btn btn-secondary"
                  title="Pick a custom date and time"
                >
                  <CalendarClock className="w-4 h-4" />
                  Custom
                </button>
              )}
            </div>
          </div>
        </div>
      )}
      
      {/* Brand Sections */}
      <div className="grid gap-6">
        {job.brands?.map(brand => {
          const output = job.brand_outputs?.[brand] || { status: 'pending' }
          const isCompleted = output.status === 'completed'
          const isScheduled = output.status === 'scheduled'
          const isFailed = output.status === 'failed'
          const isDismissed = output.status === 'dismissed'
          const isBrandGenerating = output.status === 'generating' || output.status === 'pending'
          const slot = nextSlots?.[brand]
          
          return (
            <div
              key={brand}
              className={`card overflow-hidden ${isDismissed ? 'opacity-50' : ''}`}
              style={{ borderTopColor: getBrandColor(brand), borderTopWidth: '4px' }}
            >
              {/* Brand Header */}
              <div className="p-4 border-b border-gray-100 flex items-center justify-between">
                <div className="flex items-center gap-3">
                  <BrandBadge brand={brand} size="md" />
                  <StatusBadge status={isDismissed ? 'dismissed' : output.status} />
                </div>
                
                <div className="flex items-center gap-2">
                  {slot && !isScheduled && !isDismissed && (
                    <div className="flex items-center gap-2 text-sm text-gray-500">
                      <Clock className="w-4 h-4" />
                      <span>Next slot: {slot.formatted}</span>
                    </div>
                  )}
                  {/* Dismiss / Restore button */}
                  {isDismissed ? (
                    <button
                      onClick={() => handleRestoreBrand(brand)}
                      className="flex items-center gap-1.5 px-2.5 py-1.5 text-xs font-medium text-blue-600 bg-blue-50 border border-blue-200 rounded-lg hover:bg-blue-100 transition-colors"
                      title="Restore this brand"
                    >
                      <RefreshCw className="w-3 h-3" />
                      Restore
                    </button>
                  ) : (isCompleted && !isGenerating) ? (
                    <button
                      onClick={() => handleDismissBrand(brand)}
                      className="flex items-center gap-1.5 px-2.5 py-1.5 text-xs font-medium text-red-600 bg-red-50 border border-red-200 rounded-lg hover:bg-red-100 transition-colors"
                      title="Remove this brand from scheduling"
                    >
                      <X className="w-3 h-3" />
                      Dismiss
                    </button>
                  ) : null}
                </div>
              </div>
              
              {/* Content */}
              <div className="p-4">
                {isDismissed ? (
                  <div className="text-center py-6 text-gray-400">
                    <X className="w-8 h-8 mx-auto mb-2 text-gray-300" />
                    <p className="text-sm">Brand dismissed — won't be included in Schedule All</p>
                  </div>
                ) : isBrandGenerating ? (
                  <div className="flex flex-col items-center justify-center py-12">
                    <Loader2 className="w-10 h-10 text-orange-500 animate-spin mb-4" />
                    <p className="text-gray-700 font-medium mb-2">
                      {output.progress_message || `Generating ${getBrandLabel(brand)}...`}
                    </p>
                    {typeof output.progress_percent === 'number' && (
                      <div className="w-full max-w-xs">
                        <div className="flex justify-between text-xs text-gray-500 mb-1">
                          <span>Progress</span>
                          <span>{output.progress_percent}%</span>
                        </div>
                        <div className="h-2 bg-gray-200 rounded-full overflow-hidden">
                          <div 
                            className="h-full bg-orange-500 transition-all duration-500 ease-out"
                            style={{ width: `${output.progress_percent}%` }}
                          />
                        </div>
                      </div>
                    )}
                  </div>
                ) : isFailed ? (
                  <div className="text-center py-8">
                    <AlertCircle className="w-10 h-10 text-red-500 mx-auto mb-4" />
                    <p className="text-gray-600 mb-4">{output.error || 'Generation failed'}</p>
                    <button
                      onClick={() => handleRegenerateBrand(brand)}
                      disabled={regenerateBrand.isPending}
                      className="btn btn-primary"
                    >
                      <RefreshCw className="w-4 h-4" />
                      Retry
                    </button>
                  </div>
                ) : (isCompleted || isScheduled) ? (
                  <div className="space-y-4">
                    {/* Per-brand AI prompt (auto-generated jobs) */}
                    {isAutoGenerated && output.ai_prompt && (
                      <div className="text-sm bg-purple-50 rounded-lg p-3 border border-purple-100">
                        <p className="font-medium text-purple-700 mb-1 text-xs">AI Prompt:</p>
                        <p className="text-purple-600 italic text-xs">{output.ai_prompt}</p>
                      </div>
                    )}
                    
                    {/* Main content area - Media + Content Lines side by side */}
                    <div className="grid grid-cols-1 lg:grid-cols-2 gap-4">
                      {/* Left side: Media Preview - 3 columns: IG/FB Thumbnail, YT Thumbnail, Video */}
                      <div className="grid grid-cols-3 gap-3">
                        {/* IG/FB Thumbnail */}
                        <div>
                          <p className="text-xs text-gray-500 mb-1 text-center">IG/FB</p>
                          {output.thumbnail_path ? (
                            <div className="aspect-[9/16] bg-gray-100 rounded-lg overflow-hidden">
                              <img
                                src={output.thumbnail_path}
                                alt={`${brand} thumbnail`}
                                className="w-full h-full object-cover object-top"
                              />
                            </div>
                          ) : (
                            <div className="aspect-[9/16] bg-gray-100 rounded-lg flex flex-col items-center justify-center text-gray-400 p-2">
                              <AlertCircle className="w-8 h-8 mb-1" />
                              <p className="text-xs text-center">No thumbnail</p>
                            </div>
                          )}
                        </div>
                        
                        {/* YouTube Thumbnail */}
                        <div>
                          <p className="text-xs text-gray-500 mb-1 text-center">YouTube</p>
                          {output.yt_thumbnail_path ? (
                            <div className="aspect-[9/16] bg-gray-100 rounded-lg overflow-hidden">
                              <img
                                src={output.yt_thumbnail_path}
                                alt={`${brand} YouTube thumbnail`}
                                className="w-full h-full object-cover object-top"
                              />
                            </div>
                          ) : (
                            <div className="aspect-[9/16] bg-gray-100 rounded-lg flex flex-col items-center justify-center text-gray-400 p-2">
                              <Youtube className="w-8 h-8 mb-1" />
                              <p className="text-xs text-center">No YT thumb</p>
                            </div>
                          )}
                        </div>
                        
                        {/* Video */}
                        <div>
                          <p className="text-xs text-gray-500 mb-1 text-center">Video</p>
                          {output.video_path ? (
                            <div className="aspect-[9/16] bg-black rounded-lg overflow-hidden">
                              <video
                                key={output.video_path}
                                src={output.video_path}
                                className="w-full h-full"
                                style={{ objectFit: 'contain' }}
                                controls
                                playsInline
                                preload="auto"
                                controlsList="nodownload"
                              >
                                <source src={output.video_path} type="video/mp4" />
                                Your browser does not support the video tag.
                              </video>
                            </div>
                          ) : (
                            <div className="aspect-[9/16] bg-gray-900 rounded-lg flex flex-col items-center justify-center text-gray-400 p-2">
                              <Play className="w-8 h-8 mb-1" />
                              <p className="text-xs text-center">No video</p>
                            </div>
                          )}
                        </div>
                      </div>
                      
                      {/* Right side: Title + Content Lines for this brand */}
                      <div className="bg-gray-50 rounded-lg p-4">
                        {/* Per-brand title */}
                        <div className="mb-3 pb-3 border-b border-gray-200">
                          {editingTitleBrand === brand ? (
                            <div className="flex items-start gap-2">
                              <textarea
                                value={editingTitleValue}
                                onChange={(e) => setEditingTitleValue(e.target.value)}
                                rows={2}
                                className="flex-1 px-2 py-1.5 text-sm border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent resize-none"
                                autoFocus
                                onKeyDown={(e) => {
                                  if (e.key === 'Enter' && !e.shiftKey) {
                                    e.preventDefault()
                                    saveBrandTitle()
                                  }
                                  if (e.key === 'Escape') setEditingTitleBrand(null)
                                }}
                              />
                              <button
                                onClick={saveBrandTitle}
                                disabled={savingTitle}
                                className="p-1.5 rounded hover:bg-green-100 text-green-600"
                                title="Save title"
                              >
                                {savingTitle ? (
                                  <Loader2 className="w-4 h-4 animate-spin" />
                                ) : (
                                  <Save className="w-4 h-4" />
                                )}
                              </button>
                              <button
                                onClick={() => setEditingTitleBrand(null)}
                                className="p-1.5 rounded hover:bg-gray-200 text-gray-400"
                                title="Cancel"
                              >
                                <X className="w-4 h-4" />
                              </button>
                            </div>
                          ) : (
                            <div className="flex items-start justify-between gap-2">
                              <p className="text-sm font-semibold text-gray-900 whitespace-pre-line flex-1">
                                {output.title || job.title}
                              </p>
                              {(isCompleted || isScheduled) && (
                                <button
                                  onClick={() => startEditingTitle(brand)}
                                  className="p-1 rounded hover:bg-gray-200 text-gray-400 hover:text-gray-600 flex-shrink-0"
                                  title="Edit title for this brand"
                                >
                                  <Pencil className="w-3.5 h-3.5" />
                                </button>
                              )}
                            </div>
                          )}
                        </div>
                        
                        <div className="flex items-center justify-between mb-3">
                          <span className="text-sm font-medium text-gray-700">Content (this brand)</span>
                          <button
                            onClick={() => copyToClipboard(
                              (output.content_lines || job.content_lines || []).join('\n'), 
                              'Content'
                            )}
                            className="p-1.5 rounded hover:bg-gray-200"
                            title="Copy content"
                          >
                            <Copy className="w-4 h-4 text-gray-500" />
                          </button>
                        </div>
                        <div className="space-y-2 max-h-[400px] overflow-y-auto">
                          {(output.content_lines || job.content_lines || []).map((line, idx) => (
                            <div 
                              key={idx} 
                              className="text-sm text-gray-700 py-1.5 px-2 bg-white rounded border-l-2 border-gray-300"
                            >
                              <span className="font-medium text-gray-500 mr-2">{idx + 1}.</span>
                              {line}
                            </div>
                          ))}
                        </div>
                      </div>
                    </div>
                    
                    {/* Caption */}
                    {output.caption && (
                      <div className="space-y-4">
                        {/* Instagram Caption */}
                        <div className="bg-gradient-to-r from-purple-50 to-pink-50 rounded-lg p-4 border border-purple-100">
                          <div className="flex items-center justify-between mb-2">
                            <div className="flex items-center gap-2">
                              <span className="text-lg">📸</span>
                              <span className="text-sm font-medium text-purple-700">Instagram Caption</span>
                            </div>
                            <button
                              onClick={() => copyToClipboard(output.caption!, 'Instagram Caption')}
                              className="p-1.5 rounded hover:bg-purple-100"
                            >
                              <Copy className="w-4 h-4 text-purple-500" />
                            </button>
                          </div>
                          <div className="max-h-[300px] overflow-y-auto">
                            <p className="text-sm text-gray-600 whitespace-pre-line">
                              {output.caption}
                            </p>
                          </div>
                        </div>
                        
                        {/* Facebook Caption */}
                        <div className="bg-gradient-to-r from-blue-50 to-indigo-50 rounded-lg p-4 border border-blue-100">
                          <div className="flex items-center justify-between mb-2">
                            <div className="flex items-center gap-2">
                              <span className="text-lg">📘</span>
                              <span className="text-sm font-medium text-blue-700">Facebook Caption</span>
                              <span className="text-xs text-blue-400">(shorter)</span>
                            </div>
                            <button
                              onClick={() => copyToClipboard(createFacebookCaption(output.caption!), 'Facebook Caption')}
                              className="p-1.5 rounded hover:bg-blue-100"
                            >
                              <Copy className="w-4 h-4 text-blue-500" />
                            </button>
                          </div>
                          <div className="max-h-[200px] overflow-y-auto">
                            <p className="text-sm text-gray-600 whitespace-pre-line">
                              {createFacebookCaption(output.caption!)}
                            </p>
                          </div>
                        </div>
                        
                        {/* YouTube Title & Description */}
                        <div className="bg-gradient-to-r from-red-50 to-orange-50 rounded-lg p-4 border border-red-100">
                          <div className="flex items-center justify-between mb-2">
                            <div className="flex items-center gap-2">
                              <span className="text-lg">📺</span>
                              <span className="text-sm font-medium text-red-700">YouTube Shorts</span>
                            </div>
                          </div>
                          
                          {/* YouTube Title */}
                          <div className="mb-3">
                            <div className="flex items-center justify-between mb-1">
                              <span className="text-xs font-medium text-red-600">Title</span>
                              <button
                                onClick={() => copyToClipboard(output.yt_title || job.title, 'YouTube Title')}
                                className="p-1 rounded hover:bg-red-100"
                              >
                                <Copy className="w-3.5 h-3.5 text-red-500" />
                              </button>
                            </div>
                            <p className="text-sm font-medium text-gray-800 bg-white/50 rounded px-2 py-1.5">
                              {output.yt_title || job.title}
                            </p>
                          </div>
                          
                          {/* YouTube Description (same as Facebook) */}
                          <div>
                            <div className="flex items-center justify-between mb-1">
                              <span className="text-xs font-medium text-red-600">Description</span>
                              <button
                                onClick={() => copyToClipboard(createFacebookCaption(output.caption!), 'YouTube Description')}
                                className="p-1 rounded hover:bg-red-100"
                              >
                                <Copy className="w-3.5 h-3.5 text-red-500" />
                              </button>
                            </div>
                            <div className="max-h-[120px] overflow-y-auto bg-white/50 rounded px-2 py-1.5">
                              <p className="text-sm text-gray-600 whitespace-pre-line">
                                {createFacebookCaption(output.caption!)}
                              </p>
                            </div>
                          </div>
                        </div>
                      </div>
                    )}
                    
                    {/* Scheduled Info */}
                    {isScheduled && output.scheduled_time && (
                      <div className="bg-purple-50 rounded-lg p-4 flex items-center gap-3">
                        <Check className="w-5 h-5 text-purple-600" />
                        <div>
                          <p className="font-medium text-purple-900">Scheduled</p>
                          <p className="text-sm text-purple-700">
                            {format(new Date(output.scheduled_time), 'MMMM d, yyyy h:mm a')}
                          </p>
                        </div>
                      </div>
                    )}
                    
                    {/* Actions */}
                    <div className="flex gap-2">
                      <button
                        onClick={() => handleDownload(brand, output)}
                        className="btn btn-secondary flex-1"
                      >
                        <Download className="w-4 h-4" />
                        Download
                      </button>
                      
                      {isCompleted && (
                        <>
                          <button
                            onClick={() => openBrandScheduleModal(brand)}
                            disabled={schedulingBrand === brand || isGenerating}
                            className="btn btn-success flex-1"
                          >
                            {schedulingBrand === brand ? (
                              <Loader2 className="w-4 h-4 animate-spin" />
                            ) : (
                              <Calendar className="w-4 h-4" />
                            )}
                            Schedule
                          </button>
                          
                          <button
                            onClick={() => handleRegenerateBrand(brand)}
                            disabled={regenerateBrand.isPending || isGenerating}
                            className="btn btn-secondary"
                          >
                            <RefreshCw className="w-4 h-4" />
                          </button>
                        </>
                      )}
                      
                      {isScheduled && (
                        <>
                          <button
                            onClick={() => copyToClipboard(output.caption || '', 'Caption')}
                            className="btn btn-secondary flex-1"
                          >
                            <Copy className="w-4 h-4" />
                            Copy Caption
                          </button>
                          <button
                            onClick={() => copyToClipboard(job.title || '', 'Title')}
                            className="btn btn-secondary flex-1"
                          >
                            <Copy className="w-4 h-4" />
                            Copy Title
                          </button>
                        </>
                      )}
                    </div>
                  </div>
                ) : (
                  <div className="text-center py-8 text-gray-500">
                    Waiting to generate...
                  </div>
                )}
              </div>
            </div>
          )
        })}
      </div>
      
      {/* Delete Modal */}
      <Modal
        isOpen={deleteModalOpen}
        onClose={() => setDeleteModalOpen(false)}
        title="Delete Job"
        size="sm"
      >
        <div className="space-y-4">
          <p className="text-gray-600">
            Are you sure you want to delete this job? This will also delete all generated media.
          </p>
          <div className="flex gap-3">
            <button
              onClick={() => setDeleteModalOpen(false)}
              className="btn btn-secondary flex-1"
            >
              Cancel
            </button>
            <button
              onClick={handleDelete}
              disabled={deleteJob.isPending}
              className="btn btn-danger flex-1"
            >
              {deleteJob.isPending ? (
                <Loader2 className="w-4 h-4 animate-spin" />
              ) : (
                'Delete'
              )}
            </button>
          </div>
        </div>
      </Modal>
      
      {/* Edit Title Modal */}
      <Modal
        isOpen={editTitleModalOpen}
        onClose={() => setEditTitleModalOpen(false)}
        title="Edit Title"
        size="md"
      >
        <div className="space-y-4">
          <div>
            <label className="block text-sm font-medium text-gray-700 mb-2">
              New Title
            </label>
            <textarea
              value={editedTitle}
              onChange={(e) => setEditedTitle(e.target.value)}
              rows={4}
              className="input resize-none"
              placeholder="Enter new title..."
            />
          </div>
          <p className="text-sm text-gray-500">
            Changing the title will regenerate all brand images with the new text.
          </p>
          <div className="flex gap-3">
            <button
              onClick={() => setEditTitleModalOpen(false)}
              className="btn btn-secondary flex-1"
            >
              Cancel
            </button>
            <button
              onClick={handleSaveTitle}
              disabled={updateJob.isPending || !editedTitle.trim()}
              className="btn btn-primary flex-1"
            >
              {updateJob.isPending ? (
                <Loader2 className="w-4 h-4 animate-spin" />
              ) : (
                'Save & Regenerate'
              )}
            </button>
          </div>
        </div>
      </Modal>
      
      {/* Per-brand Schedule Options Modal */}
      {brandScheduleModalBrand && (
        <Modal
          isOpen={!!brandScheduleModalBrand}
          onClose={() => setBrandScheduleModalBrand(null)}
          title={`Schedule — ${brandScheduleModalBrand ? getBrandLabel(brandScheduleModalBrand) : ''}`}
          size="md"
        >
          <div className="space-y-4">
            {/* Mode selection */}
            <div className="grid grid-cols-2 gap-3">
              <button
                onClick={() => setBrandScheduleMode('auto')}
                className={`flex flex-col items-center gap-2 p-4 rounded-xl border-2 transition-all ${
                  brandScheduleMode === 'auto'
                    ? 'border-purple-500 bg-purple-50'
                    : 'border-gray-200 hover:border-gray-300'
                }`}
              >
                <Calendar className={`w-5 h-5 ${brandScheduleMode === 'auto' ? 'text-purple-600' : 'text-gray-400'}`} />
                <span className={`text-sm font-medium ${brandScheduleMode === 'auto' ? 'text-purple-700' : 'text-gray-600'}`}>
                  Schedule Now
                </span>
                <span className="text-[10px] text-gray-400 text-center">Next available time</span>
              </button>
              <button
                onClick={() => setBrandScheduleMode('custom')}
                className={`flex flex-col items-center gap-2 p-4 rounded-xl border-2 transition-all ${
                  brandScheduleMode === 'custom'
                    ? 'border-purple-500 bg-purple-50'
                    : 'border-gray-200 hover:border-gray-300'
                }`}
              >
                <Clock className={`w-5 h-5 ${brandScheduleMode === 'custom' ? 'text-purple-600' : 'text-gray-400'}`} />
                <span className={`text-sm font-medium ${brandScheduleMode === 'custom' ? 'text-purple-700' : 'text-gray-600'}`}>
                  Custom Time
                </span>
                <span className="text-[10px] text-gray-400 text-center">Pick date & time</span>
              </button>
            </div>

            {/* Custom date/time picker */}
            {brandScheduleMode === 'custom' && (
              <div className="grid grid-cols-2 gap-4">
                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-1">Date</label>
                  <input
                    type="date"
                    value={brandCustomDate}
                    min={new Date().toISOString().split('T')[0]}
                    onChange={(e) => setBrandCustomDate(e.target.value)}
                    className="input"
                  />
                </div>
                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-1">Time</label>
                  <input
                    type="time"
                    value={brandCustomTime}
                    onChange={(e) => setBrandCustomTime(e.target.value)}
                    className="input"
                  />
                </div>
              </div>
            )}

            {/* Confirm */}
            <div className="flex gap-3 pt-2">
              <button
                onClick={() => setBrandScheduleModalBrand(null)}
                className="btn btn-secondary flex-1"
              >
                Cancel
              </button>
              <button
                onClick={confirmBrandSchedule}
                disabled={brandScheduleMode === 'custom' && (!brandCustomDate || !brandCustomTime)}
                className="btn btn-primary flex-1"
              >
                <Calendar className="w-4 h-4" />
                {brandScheduleMode === 'auto' ? 'Schedule Now' : 'Schedule'}
              </button>
            </div>
          </div>
        </Modal>
      )}

      {/* Custom Schedule Modal */}
      <Modal
        isOpen={customScheduleModalOpen}
        onClose={() => setCustomScheduleModalOpen(false)}
        title="Custom Schedule"
        size="md"
      >
        <div className="space-y-4">
          <p className="text-gray-600">
            Choose a date and time to schedule {completedCount === 1 ? 'this brand' : scheduledCount > 0 ? `the ${completedCount} remaining brands` : `all ${completedCount} brands`}.
            {completedCount > 1 && 'Brands will be staggered by 1 hour each.'}
          </p>
          
          <div className="grid grid-cols-2 gap-4">
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-2">
                Date
              </label>
              <input
                type="date"
                value={customScheduleDate}
                onChange={(e) => setCustomScheduleDate(e.target.value)}
                min={new Date().toISOString().split('T')[0]}
                className="input"
              />
            </div>
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-2">
                Start Time
              </label>
              <input
                type="time"
                value={customScheduleTime}
                onChange={(e) => setCustomScheduleTime(e.target.value)}
                className="input"
              />
            </div>
          </div>
          
          {customScheduleDate && customScheduleTime && completedCount > 0 && (
            <div className="bg-gray-50 p-3 rounded-lg text-sm text-gray-600">
              <p className="font-medium mb-1">Schedule Preview:</p>
              <ul className="space-y-1">
                {Object.entries(job?.brand_outputs || {})
                  .filter(([_, output]) => output.status === 'completed')
                  .map(([brand], index) => {
                    const baseTime = new Date(`${customScheduleDate}T${customScheduleTime}`)
                    baseTime.setHours(baseTime.getHours() + index)
                    return (
                      <li key={brand} className="flex items-center gap-2">
                        <span className="capitalize">{brand}</span>
                        <span className="text-gray-400">→</span>
                        <span>{format(baseTime, 'MMM d, h:mm a')}</span>
                      </li>
                    )
                  })}
              </ul>
            </div>
          )}
          
          <div className="flex gap-3">
            <button
              onClick={() => setCustomScheduleModalOpen(false)}
              className="btn btn-secondary flex-1"
            >
              Cancel
            </button>
            <button
              onClick={handleCustomScheduleAll}
              disabled={schedulingCustom || !customScheduleDate || !customScheduleTime}
              className="btn btn-primary flex-1"
            >
              {schedulingCustom ? (
                <Loader2 className="w-4 h-4 animate-spin" />
              ) : (
                <>
                  <CalendarClock className="w-4 h-4" />
                  {scheduleButtonLabel}
                </>
              )}
            </button>
          </div>
        </div>
      </Modal>
    </div>
  )
}
