#!/usr/bin/env python3
"""
Migration: Backfill created_by="toby" for all existing ScheduledReel entries.

This migration marks all existing scheduled reels as Toby-created, since they were
all generated by Toby before the manual upload feature was added.

Only new manual uploads should have created_by="user".
"""
import os
import sys
from datetime import datetime, timezone

# Add the app root to sys.path
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from app.db_connection import SessionLocal
from app.models.scheduling import ScheduledReel


def run_migration():
    """Backfill created_by for all existing entries."""
    db = SessionLocal()
    try:
        # Find all entries where created_by is NULL or empty
        legacy_entries = db.query(ScheduledReel).filter(
            (ScheduledReel.created_by == None) | (ScheduledReel.created_by == "")
        ).all()
        
        if not legacy_entries:
            print("✅ No legacy entries to backfill — all entries already have created_by set")
            return
        
        print(f"🔄 Backfilling {len(legacy_entries)} existing entries with created_by='toby'...")
        
        # Mark all as toby-created
        for entry in legacy_entries:
            entry.created_by = "toby"
            print(f"   ✓ {entry.schedule_id} → toby")
        
        db.commit()
        print(f"\n✅ Migration complete! Backfilled {len(legacy_entries)} entries")
        
    except Exception as e:
        db.rollback()
        print(f"\n❌ Migration failed: {e}")
        import traceback
        traceback.print_exc()
        sys.exit(1)
    finally:
        db.close()


if __name__ == "__main__":
    print("=" * 80)
    print("MIGRATION: Backfill created_by for existing ScheduledReel entries")
    print("=" * 80)
    run_migration()
    print("=" * 80)
